// Questões exclusivas para as aulas que antes dependiam de uma revisão geral
// do módulo. Cada item aponta para a própria seção da aula e usa um trecho
// literal do POP como fundamento. Isso permite avaliar o objetivo específico,
// sem transformar uma pergunta apenas relacionada ao tema em prova da aula.
export const QUESTOES_COBERTURA = [
  // M00 — orientação e controle documental
  ['m00', 'Qual é o efeito da data-base registrada no controle documental do POP?',
    ['Dispensa nova conferência normativa quando a minuta já passou por revisão editorial', 'Não substitui nova conferência antes da aprovação nem a validação da norma no caso concreto', 'Fixa definitivamente as normas aplicáveis a todos os processos iniciados antes daquela data'], 1,
    'A data-base informa quando a verificação foi feita, mas não encerra a conferência normativa do processo concreto.',
    { sec: 'pop-section-001', quote: 'A data-base não substitui nova conferência antes da aprovação institucional nem a validação da norma aplicável ao processo concreto.' }],
  // A pergunta era sobre a versão 1.6, e o histórico do POP v1.9 não traz mais
  // essa linha: a tabela passou a listar 1.0, 1.8 e 1.9. Reescrita sobre a
  // entrada que existe hoje, em vez de citar um trecho que sumiu da fonte.
  ['m00', 'O que a versão 1.9 registrou no histórico de evolução do POP?',
    ['A substituição integral do licenciamento trifásico por um procedimento ambiental simplificado', 'A inclusão da Portaria IAT nº 42/2022 e do Diagnóstico Climático nos pontos aplicáveis ao EIA/RIMA', 'A retirada dos controles anuais aplicáveis aos acordos de cooperação técnica atualmente vigentes'], 1,
    'O histórico permite identificar qual conteúdo entrou em cada revisão do documento.',
    { sec: 'pop-section-002', quote: 'Inclusão da Portaria IAT nº 42/2022 e do Diagnóstico Climático nos pontos aplicáveis ao EIA/RIMA' }],

  // M01 — definições e método obrigatório
  ['m01', 'No vocabulário do POP, qual é a função do Memorial?',
    ['Substituir o estudo ambiental ao consolidar todas as conclusões sobre impactos e medidas mitigadoras', 'Caracterizar o arranjo, as estruturas, os parâmetros técnicos e os principais dados do empreendimento', 'Autorizar a implantação ao comprovar a compatibilidade entre a licença, a outorga e o ato setorial'], 1,
    'O Memorial caracteriza tecnicamente o empreendimento; ele não assume a função de estudo ambiental ou licença.',
    { sec: 'pop-section-009', quote: 'Documento de engenharia e caracterização do arranjo, estruturas, parâmetros técnicos, coordenadas, potência, vazões, reservatório, acessos e sistemas associados.' }],
  ['m01', 'Se o sistema ou um ato institucional usar uma denominação específica, qual identificação deve prevalecer?',
    ['A denominação mais conhecida pela equipe, desde que seja explicada na conclusão do documento', 'A identificação oficial vigente no sistema, na norma setorial ou no ato institucional', 'A sigla adotada pelo requerente no primeiro protocolo, ainda que tenha sido atualizada depois'], 1,
    'A terminologia do produto técnico deve acompanhar a identificação oficial aplicável.',
    { sec: 'pop-section-010', quote: 'deve prevalecer a identificação oficial vigente' }],
  ['m01', 'O que torna uma manifestação técnica rastreável segundo o POP?',
    ['Informar apenas a conclusão e remeter toda a fundamentação aos anexos protocolados pelo requerente', 'Permitir reconhecer o documento, sua exigibilidade e suficiência, a consequência da lacuna e a providência', 'Reproduzir a lista do Termo de Referência e marcar os arquivos presentes, sem avaliar seu conteúdo material'], 1,
    'Rastreabilidade conecta a evidência analisada ao juízo técnico e ao encaminhamento adotado.',
    { sec: 'pop-section-011', quote: 'O leitor deve compreender qual documento foi analisado, por que ele é exigível, se seu conteúdo é suficiente, qual consequência decorre da lacuna e qual providência é proporcional à fase do processo.' }],
  ['m01', 'Depois de registrar a consequência técnica de uma pendência, como deve ser definido o encaminhamento?',
    ['Pelo modelo utilizado no processo anterior, para manter exatamente a mesma providência em todos os casos', 'De forma proporcional à fase, ao risco identificado e à possibilidade de saneamento', 'Pela quantidade de documentos ausentes, sem considerar o efeito da lacuna sobre a decisão'], 1,
    'A sequência obrigatória liga a providência à fase, ao risco e à possibilidade real de corrigir a lacuna.',
    { sec: 'pop-section-012', quote: 'Definir encaminhamento proporcional à fase, ao risco e à possibilidade de saneamento.' }],
  ['m01', 'Como classificar um documento que existe, mas não contém os dados mínimos para a decisão técnica?',
    ['Apresenta, pois a presença formal do arquivo encerra a verificação documental daquela etapa', 'Insuficiente, porque o conteúdo apresentado não sustenta a decisão técnica necessária', 'Inconsistente, ainda que não exista divergência interna ou conflito com outra evidência do processo'], 1,
    'A classificação “Insuficiente” distingue presença formal de suficiência material.',
    { sec: 'pop-section-013', quote: 'Documento existe, mas não contém dados mínimos para decisão técnica.' }],
  ['m01', 'Quando uma pendência impede a decisão?',
    ['Quando exige apenas ajuste de forma que não modifica a compreensão nem a segurança da decisão', 'Quando impede decisão segura ou envolve tema essencial de enquadramento, viabilidade ou regularidade', 'Quando qualquer campo secundário está vazio, independentemente da consequência para a análise'], 1,
    'O impedimento decorre da consequência da lacuna, e não apenas da existência de uma falha.',
    // A fonte anterior definia uma escala ordinal que saiu do POP. O critério
    // atual está na seção 25 e decorre diretamente da consequência.
    { sec: 'pop-section-098', quote: 'A conclusão deve decorrer da consequência técnica e da possibilidade de saneamento dos achados.' }],

  // M03 — enquadramento e Consulta Prévia
  ['m03', 'Qual é a finalidade prática da Licença Prévia na matriz de enquadramento?',
    ['Autorizar a operação comercial e consolidar o atendimento das condicionantes da instalação', 'Aprovar a localização e a concepção do empreendimento analisado', 'Autorizar as obras e os programas ambientais previstos no projeto executivo'], 1,
    'A finalidade da LP é distinta das autorizações de instalação e de operação.',
    { sec: 'pop-section-021', quote: 'Aprova localização e concepção.' }],
  ['m03', 'O que a matriz mínima de enquadramento da IN IAT nº 09/2025 não substitui?',
    ['A conferência do cadastro e dos arquivos entregues quando o processo já possui licença anterior', 'A leitura do art. 9º, do Quadro 1, dos Termos de Referência e das peculiaridades do processo', 'A escolha do formulário eletrônico indicado pelo requerente para iniciar a instrução administrativa'], 1,
    'A matriz funciona como roteiro de conferência e precisa ser aplicada junto das fontes e do caso concreto.',
    { sec: 'pop-section-022', quote: 'não substitui a leitura do art. 9º, do Quadro 1, dos Termos de Referência vigentes e das peculiaridades do processo' }],
  ['m03', 'No checklist da Consulta Prévia, como tratar um KML que contém somente um ponto para um arranjo complexo?',
    ['Aceitar o ponto como delimitação integral quando ele coincide com a posição aproximada da barragem', 'Não aceitar apenas o ponto isolado quando a complexidade do arranjo exige outras geometrias', 'Converter o ponto em uma área circular padronizada e prosseguir sem solicitar arquivo complementar'], 1,
    'Um arranjo complexo precisa ser espacialmente representado de modo compatível com a análise.',
    { sec: 'pop-section-026', quote: 'Não aceitar apenas ponto isolado quando houver arranjo complexo.' }],
  ['m03', 'O que a conclusão da Consulta Prévia não deve declarar?',
    ['Quais documentos e estudos deverão instruir o pedido futuro de licenciamento ambiental', 'A viabilidade ambiental definitiva do empreendimento apresentado pelo requerente', 'Se os elementos disponíveis permitem orientar os próximos passos do interessado'], 1,
    'A Consulta Prévia orienta a instrução futura, mas não antecipa a decisão definitiva de viabilidade.',
    { sec: 'pop-section-133', quote: 'Não deve declarar viabilidade ambiental definitiva.' }],

  // M04 — LAS
  ['m04', 'Como o checklist da LAS orienta a conferência do ato setorial para uma CGH?',
    ['Exigir sempre o mesmo ato aplicável às demais tipologias, mesmo quando ele não for adequado à CGH', 'Não exigir ato inadequado, mas conferir a documentação setorial que seja aplicável à CGH', 'Dispensar toda documentação setorial porque a CGH está sujeita apenas ao controle ambiental estadual'], 1,
    'A exigência deve corresponder à tipologia e ao ato setorial efetivamente aplicável.',
    { sec: 'pop-section-032', quote: 'Não exigir ato inadequado para CGH, mas exigir documentação setorial aplicável.' }],

  // M05 — rito trifásico
  ['m05', 'Ao analisar o estudo ambiental apresentado para a LP, quais elementos devem ser verificados?',
    ['Somente a assinatura, a ART e a correspondência do título com o Termo de Referência', 'Diagnóstico, alternativas, impactos, medidas e programas apresentados para a decisão', 'Apenas o cronograma de implantação e o custo previsto de cada programa ambiental'], 1,
    'Na LP, a análise do estudo precisa alcançar os elementos que sustentam o juízo de viabilidade.',
    { sec: 'pop-section-035', quote: 'Verificar diagnóstico, alternativas, impactos, medidas e programas.' }],
  ['m05', 'Como deve ser tratado, no checklist da LI, um programa genérico sem execução verificável?',
    ['Como suficiente se tiver sido mencionado no estudo aprovado durante a fase de Licença Prévia', 'Não deve ser aceito como programa suficiente para acompanhar a execução da medida', 'Como condicionante automaticamente cumprida após a apresentação do primeiro cronograma'], 1,
    'Um programa da LI precisa permitir execução, acompanhamento e comprovação.',
    { sec: 'pop-section-037', quote: 'Não aceitar programa genérico sem execução verificável.' }],
  ['m05', 'Na análise de condicionantes para a LO, quais registros precisam ser distinguidos?',
    ['O status declarado pelo empreendedor e o status efetivamente validado pelo IAT', 'O número da licença anterior e o número do protocolo usado para pedir a operação', 'A data de elaboração do relatório e a data da assinatura do responsável técnico'], 0,
    'A declaração do empreendedor é uma evidência de entrada; a validação do órgão é um juízo técnico distinto.',
    { sec: 'pop-section-039', quote: 'Diferenciar status do empreendedor e status validado pelo IAT.' }],

  // M06 — situações especiais
  ['m06', 'Para que a Autorização Ambiental não pode ser utilizada?',
    ['Para definir controles pontuais de uma atividade temporária devidamente delimitada no processo', 'Para contornar restrição territorial ou autorizar ampliação incompatível com o Plano de Manejo', 'Para estabelecer prazo e relatório de encerramento compatíveis com a atividade autorizada'], 1,
    'A AA não converte incompatibilidade territorial ou ampliação relevante em intervenção pontual.',
    { sec: 'pop-section-042', quote: 'AA não pode ser utilizada para contornar restrição territorial ou autorizar ampliação incompatível com o Plano de Manejo.' }],
  ['m06', 'Em uma RLO com possível execução federal delegada, quando o IAT pode concluir sobre sua competência?',
    ['Quando o requerente informa no protocolo que existe cooperação anterior entre os dois órgãos ambientais', 'Depois de comprovar o fundamento e o alcance da delegação aplicável à fase analisada', 'Sempre que o empreendimento já recebeu alguma licença ambiental emitida pelo Estado'], 1,
    'A existência e o escopo da delegação precisam ser demonstrados antes da conclusão de competência.',
    { sec: 'pop-section-045', quote: 'Não concluir pela competência do IAT sem comprovação do fundamento e do alcance da delegação.' }],
  ['m06', 'A LOC da Lei Federal nº 15.190/2025 equivale automaticamente às modalidades estaduais de regularização?',
    ['Sim, porque toda licença corretiva possui o mesmo objeto e segue uma única regra de transição', 'Não; a decisão exige leitura conjunta da situação, da etapa, da transição e da regulamentação do IAT', 'Sim, desde que a obra esteja concluída e o empreendedor já tenha iniciado a operação comercial'], 1,
    'A semelhança de finalidade não autoriza tratar modalidades de regimes diferentes como sinônimos automáticos.',
    { sec: 'pop-section-047', quote: 'A LOC da Lei Federal nº 15.190/2025 não deve ser tratada como sinônimo automático das modalidades estaduais.' }],
  ['m06', 'Qual elemento é indispensável para uma transferência segura de titularidade?',
    ['A simples atualização do nome do requerente no cadastro eletrônico, sem alteração dos demais atos', 'O termo de assunção das condicionantes, dos passivos e das obrigações aplicáveis', 'Uma declaração unilateral do novo titular informando que conhece a existência da licença anterior'], 1,
    'A transferência precisa documentar quem assume as obrigações e os passivos vinculados ao empreendimento.',
    { sec: 'pop-section-049', quote: 'Sem assunção não há transferência segura.' }],

  // M07 — sistemas associados e segurança
  ['m07', 'Ao identificar uma linha ou subestação associada, qual definição deve ser feita primeiro?',
    ['Se a estrutura integra o escopo analisado ou se exige licenciamento específico', 'Se o custo da estrutura será informado no mesmo relatório financeiro da usina', 'Se a operação poderá começar antes da conclusão das demais estruturas do empreendimento'], 0,
    'A delimitação de escopo evita omissão e também evita incorporar automaticamente estrutura sujeita a processo próprio.',
    { sec: 'pop-section-052', quote: 'Definir se integra o escopo ou exige licença específica.' }],
  ['m07', 'Ao verificar o PAE, até onde vai a análise ambiental indicada pelo POP?',
    ['Aprovar a estabilidade estrutural da barragem com base nas rotas de fuga e nos pontos de encontro', 'Compatibilizar o plano com comunidades, programas e zoneamento, sem concluir sobre estabilidade estrutural', 'Substituir a avaliação do órgão fiscalizador sempre que a zona de autossalvamento alcançar uma comunidade'], 1,
    'A equipe ambiental verifica interfaces do PAE, respeitando o limite da competência estrutural.',
    { sec: 'pop-section-055', quote: 'Compatibilizar com comunidades, programas ambientais e zoneamento, sem concluir estabilidade estrutural.' }],

  // M08 — documentos e estudos ambientais
  ['m08', 'Qual é a função do RIMA em relação ao EIA?',
    ['Acrescentar impactos não examinados no EIA para ampliar o debate durante a participação pública', 'Comunicar ao público, com fidelidade e linguagem acessível, as conclusões do EIA', 'Substituir o EIA quando a apresentação pública contém mapas, alternativas e medidas ambientais'], 1,
    'O RIMA torna as conclusões acessíveis sem alterar ou substituir o estudo que lhes dá suporte.',
    { sec: 'pop-section-059', quote: 'Comunica ao público, com fidelidade e linguagem acessível, as conclusões do EIA.' }],
  ['m08', 'Como deve ser escolhido o Termo de Referência usado para analisar um PCA?',
    ['Combinando automaticamente os requisitos de todos os modelos disponíveis para ampliar a segurança', 'Confirmando no processo e na fonte oficial qual Termo de Referência é aplicável', 'Adotando sempre a versão mais extensa, independentemente da fase e do objeto do requerimento'], 1,
    'A escolha do TR é vinculada ao processo e à fonte oficial, sem montagem automática de requisitos.',
    { sec: 'pop-section-061', quote: 'A escolha do TR deve ser confirmada no processo e na fonte oficial, sem combinação automática de requisitos.' }],
  ['m08', 'O caráter simplificado do RAS permite omitir dados essenciais à decisão?',
    ['Sim, desde que os dados sejam prometidos para a fase posterior por meio de condicionante genérica', 'Não; a simplificação não autoriza a ausência dos dados essenciais para avaliar o empreendimento', 'Sim, quando houver diagnóstico regional, independentemente dos dados específicos do local'], 1,
    'Simplificação reduz complexidade procedimental, não o mínimo necessário para uma decisão fundamentada.',
    { sec: 'pop-section-062', quote: 'Simplificação não autoriza ausência de dados essenciais' }],
  ['m08', 'Qual decisão o EIA deve permitir que a análise ambiental fundamente?',
    ['A definição do valor econômico de todas as medidas e dos programas previstos para a implantação', 'A decisão sobre a viabilidade ambiental do empreendimento e de suas alternativas', 'A emissão automática da licença de operação após a aprovação dos programas ambientais'], 1,
    'O EIA organiza a base analítica necessária ao juízo de viabilidade ambiental.',
    { sec: 'pop-section-064', quote: 'O EIA deve permitir decisão sobre viabilidade ambiental.' }],
  ['m08', 'Qual critério demonstra fidelidade do RIMA ao EIA?',
    ['Síntese coerente, sem alterar os impactos, as alternativas, as medidas ou a conclusão do EIA', 'Texto mais curto que elimine resultados complexos e apresente somente a alternativa escolhida', 'Inclusão de novas conclusões formuladas durante a audiência, mesmo sem respaldo no estudo original'], 0,
    'Linguagem acessível não autoriza modificar o conteúdo técnico que está sendo comunicado.',
    { sec: 'pop-section-065', quote: 'Síntese coerente com o EIA, sem alterar impactos, alternativas, medidas ou conclusão.' }],
  ['m08', 'Qual é a função do PBA após o EIA e o RIMA?',
    ['Reabrir a escolha locacional sem considerar a decisão formada na etapa de viabilidade ambiental', 'Detalhar os programas decorrentes dos estudos para permitir execução e acompanhamento', 'Substituir os relatórios de execução por uma descrição única das intenções do empreendedor'], 1,
    'O PBA transforma os programas derivados dos estudos em instrumentos executáveis e acompanháveis.',
    { sec: 'pop-section-066', quote: 'O PBA detalha os programas decorrentes do EIA e do RIMA para execução e acompanhamento.' }],
  ['m08', 'O nome “RCA”, “RCE” ou “estudo complementar” basta para demonstrar a suficiência do documento?',
    ['Sim, porque a denominação define de modo uniforme o conteúdo mínimo exigível em qualquer fase', 'Não; é preciso confirmar finalidade, conteúdo, fase, objeto e relação com os demais estudos', 'Sim, quando o arquivo possui assinatura digital e responsabilidade técnica válida para o empreendimento'], 1,
    'A análise parte do fundamento e da função exigida para o documento, não apenas do título usado no arquivo.',
    { sec: 'pop-section-073', quote: 'O nome do documento não define, por si só, sua suficiência.' }],
  ['m08', 'Quando um documento deve ser classificado como “Pendente de validação”?',
    ['Quando há divergência interna já comprovada entre o documento e a outorga ou o projeto apresentado', 'Quando a conclusão depende de sistema oficial, autorização, interveniente, versão de TR ou unidade especializada', 'Quando o documento existe, mas omite dado essencial que pode ser solicitado diretamente ao empreendedor'], 1,
    'Essa classificação explicita uma dependência que precisa ser resolvida antes do mérito correspondente.',
    { sec: 'pop-section-075', quote: 'Depende de sistema oficial, autorização, interveniente, versão de TR ou unidade especializada.' }],

  // M09 — PACUERA
  ['m09', 'Qual abrangência mínima integra a área de estudo do PACUERA indicada no POP?',
    ['Somente a APP do reservatório e os lotes diretamente confrontantes, excluídos o TVR e o trecho a jusante', 'Faixa de 1.000 m no entorno, todo o TVR e extensões mínimas a jusante e, em cascata, a montante', 'Apenas a área inundada e uma faixa uniforme de 100 m, independentemente do arranjo e da posição de outra usina'], 1,
    'A área de estudo combina entorno do reservatório, TVR e trechos que permitem analisar as relações territoriais do arranjo.',
    { sec: 'pop-section-069', quote: 'Faixa mínima de 1.000 m no entorno, totalidade do TVR, extensão mínima de 1.000 m a jusante da casa de força e, em cascata, 1.000 m a montante da usina imediatamente a jusante.' }],
  ['m09', 'Qual limite institucional deve ser respeitado na análise do PACUERA?',
    ['A unidade deve decidir também matérias urbanísticas, hídricas e estruturais para consolidar uma única conclusão', 'A unidade não deve concluir sobre matéria fora de sua competência técnica ou administrativa', 'A manifestação de outros órgãos pode ser dispensada quando o zoneamento proposto é ambientalmente conservador'], 1,
    'A integração das interfaces não transfere à unidade atribuições que pertencem a outros setores ou órgãos.',
    { sec: 'pop-section-071', quote: 'Não concluir sobre matéria urbanística, minerária, patrimonial, hídrica ou estrutural fora da competência da unidade.' }],

  // M10 — cartografia e normas materiais
  ['m10', 'No checklist cartográfico, como deve ser tratado um arquivo vetorial com somente um ponto?',
    ['Como representação suficiente de todas as estruturas quando o nome da usina aparece nos atributos do arquivo', 'Não deve ser aceito como única geometria para representar um empreendimento complexo', 'Deve ser ampliado visualmente no mapa até ocupar a área aproximada indicada no memorial descritivo'], 1,
    'Geometrias completas são necessárias quando a análise depende de delimitar estruturas e impactos.',
    { sec: 'pop-section-078', quote: 'Não aceitar apenas ponto isolado para empreendimento complexo.' }],
  ['m10', 'Como as bases institucionais de UCs, Planos de Manejo e GeoPR devem apoiar uma decisão territorial?',
    ['Como substitutas definitivas do ato de criação e dos documentos legais quando a camada possui atualização recente', 'Como fontes oficiais de triagem, com validação do ato legal quando a informação for decisiva', 'Como ilustração facultativa, sem necessidade de registrar fonte, data ou limitações da informação consultada'], 1,
    'A camada orienta a triagem espacial; a conclusão decisiva precisa ser compatibilizada com o ato jurídico aplicável.',
    { sec: 'pop-section-081', quote: 'Utilizar Dados sobre UCs, Planos de Manejo e GeoPR como fontes oficiais de triagem, com validação do ato legal quando a informação for decisiva.' }],

  // M15 — Unidades de Conservação
  ['m15', 'Por que a presença de uma Unidade de Conservação precisa ser examinada desde o enquadramento?',
    ['Porque sempre impede qualquer hidrelétrica, sem necessidade de verificar categoria, zona, fase ou estrutura afetada', 'Porque pode alterar mérito locacional, estudo, modalidade, arranjo, medidas e interfaces institucionais', 'Porque substitui a análise do empreendimento principal pela aplicação exclusiva do Plano de Manejo'], 1,
    'O efeito depende do regime, da localização e da fase, mas pode alcançar vários componentes da decisão.',
    { sec: 'pop-section-084', quote: 'A presença de Unidade de Conservação pode alterar o mérito locacional, o estudo exigido, a modalidade, o desenho do arranjo, as medidas ambientais, a participação de órgãos gestores e as condições de instalação ou operação.' }],
  ['m15', 'Em uma RLO, deve-se exigir automaticamente nova análise locacional completa por existir Unidade de Conservação?',
    ['Sim, toda renovação reinicia a viabilidade e invalida as manifestações produzidas nas fases anteriores', 'Não; primeiro se verificam histórico, atos, condicionantes, mudanças, ampliação e demais fatos novos', 'Não, porque regras territoriais nunca podem produzir efeito sobre a operação de empreendimento já instalado'], 1,
    'A renovação considera a situação consolidada e procura fatos novos com repercussão na fase atual.',
    { sec: 'pop-section-136', quote: 'Não exigir automaticamente nova análise locacional completa ou nova manifestação do órgão gestor sem fato novo.' }],

  // M11 — interfaces e vistoria
  ['m11', 'O que fazer quando um tema extrapola a atribuição técnica da unidade de licenciamento?',
    ['Concluir provisoriamente o mérito e encaminhar o processo apenas depois da emissão da licença correspondente', 'Delimitar as questões e encaminhar o tema à unidade técnica competente no fluxo vigente', 'Repetir a manifestação do requerente como conclusão institucional para evitar atraso na análise'], 1,
    'O encaminhamento especializado deve identificar com precisão a questão que depende de outra competência.',
    { sec: 'pop-section-085', quote: 'O analista deve delimitar o objeto do encaminhamento, registrar as questões que dependem de manifestação especializada e evitar conclusão de mérito fora de sua atribuição.' }],
  ['m11', 'Durante a vistoria, a observação de campo pode definir sozinha o limite jurídico de uma Unidade de Conservação?',
    ['Sim, desde que as fotografias estejam georreferenciadas e tenham sido registradas por dois técnicos', 'Não; a posição observada deve ser confrontada com cartografia oficial e Plano de Manejo', 'Sim, quando a equipe consegue visualizar em campo uma mudança clara de uso e cobertura do solo'], 1,
    'A vistoria registra evidências físicas, mas o limite jurídico depende das fontes oficiais aplicáveis.',
    { sec: 'pop-section-088', quote: 'não definir limite jurídico apenas por observação de campo' }],

  // M16 — competência federal delegada
  ['m16', 'Qual distinção deve abrir a análise de um processo com indício de delegação pelo Ibama?',
    ['Separar a competência federal originária da execução administrativa delegada ao IAT', 'Separar os custos federais dos custos estaduais antes de conferir o objeto do acordo', 'Separar as licenças emitidas antes e depois do primeiro protocolo, sem examinar o instrumento de delegação'], 0,
    'A delegação da execução não altera, por si só, a origem da competência.',
    { sec: 'pop-section-143', quote: 'separar a definição da competência do ente da execução administrativa delegada ao IAT' }],
  ['m16', 'Como deve ser organizado o controle das obrigações de um ACT?',
    ['Em arquivo pessoal do servidor que acompanha o processo, atualizado apenas durante a preparação do relatório anual', 'Em base setorial atualizada, sem depender exclusivamente da memória ou do arquivo pessoal de um servidor', 'Em registros reconstruídos ao fim de cada exercício a partir das mensagens e dos documentos que forem localizados'], 1,
    'O controle é institucional e contínuo para permanecer auditável mesmo quando a equipe muda.',
    { sec: 'pop-section-146', quote: 'A organização do RTAA e das comunicações não deve depender exclusivamente da memória ou do arquivo pessoal de um servidor.' }],
  ['m16', 'O formulário eletrônico usado pelo Ibama em 2026 deve ser tratado como modelo permanente?',
    ['Sim, porque os mesmos campos se tornam obrigatórios para qualquer ACT e para todos os exercícios seguintes', 'Não; é preciso conferir a orientação e o formulário efetivamente vigentes em cada exercício', 'Sim, salvo quando o empreendedor solicitar formalmente a substituição por um relatório textual próprio'], 1,
    'O formulário de 2026 é referência operacional histórica, não uma regra imutável.',
    { sec: 'pop-section-148', quote: 'O uso do formulário eletrônico em 2026 não deve ser tratado como regra imutável para exercícios futuros.' }],
  ['m16', 'Toda hidrelétrica situada na bacia do rio Tibagi é automaticamente de competência federal?',
    ['Sim, pois o histórico judicial da bacia transfere todos os processos atuais ao órgão ambiental federal', 'Não; devem ser identificados a decisão aplicável, o processo federal e o ACT vigente, quando houver', 'Não, porque a localização na bacia exclui qualquer possibilidade de competência originária da União'], 1,
    'O histórico regional não substitui a verificação do fundamento aplicável a cada empreendimento.',
    { sec: 'pop-section-151', quote: 'Essa circunstância não autoriza uma regra genérica de que toda hidrelétrica localizada na bacia é automaticamente de competência federal.' }],

  // M12 — suficiência, conclusão e compensação
  ['m12', 'O checklist documental cumpre sua função ao registrar apenas que um arquivo está presente?',
    ['Sim, porque a suficiência material pertence exclusivamente à etapa final de conclusão do processo', 'Não; deve avaliar também a compatibilidade do conteúdo com os elementos relevantes do processo', 'Sim, desde que todos os nomes de arquivo correspondam à lista do Termo de Referência aplicável'], 1,
    'O checklist integra controle documental e técnico, portanto vai além da presença formal.',
    { sec: 'pop-section-089', quote: 'Ele não deve apenas indicar presença de arquivo.' }],
  ['m12', 'Na estrutura mínima da Informação Técnica, o que deve ser separado na conclusão?',
    ['A adequação da modalidade e a suficiência documental do conjunto analisado', 'A assinatura do elaborador e a identificação da unidade responsável pela revisão', 'A cartografia do empreendimento e os registros fotográficos produzidos na vistoria'], 0,
    'Modalidade adequada não prova, por si só, que a documentação é suficiente para decidir.',
    { sec: 'pop-section-091', quote: 'Conclusão separando adequação da modalidade e suficiência documental.' }],
  ['m12', 'Se a modalidade requerida não for adequada, como a conclusão deve ser redigida?',
    ['Somente como lista de documentos faltantes, deixando o enquadramento para análise em uma fase posterior', 'Em redação separada, com fundamento e indicação de readequação e instrução compatível', 'Como deferimento condicionado à troca automática da modalidade depois da emissão da licença'], 1,
    'O problema de enquadramento não deve ser confundido com insuficiência documental.',
    { sec: 'pop-section-093', quote: 'Quando a modalidade não for adequada, redigir de forma separada' }],
  ['m12', 'Na LI, uma obrigação que o art. 9º do Decreto Estadual nº 7.150/2024 exige antes da emissão pode ser transferida para condicionante posterior?',
    ['Sim, sempre que a condicionante tiver prazo curto e indicar o documento comprobatório esperado', 'Não, quando o dispositivo exige que a obrigação esteja atendida antes da emissão da licença', 'Sim, se o impacto já foi descrito no estudo e existe previsão de acompanhamento pela equipe'], 1,
    'A condicionante não pode deslocar para depois um requisito legal definido para momento anterior à LI.',
    { sec: 'pop-section-096', quote: 'não transferir para condicionante posterior obrigação que o art. 9º exige antes da emissão da LI' }],
  ['m12', 'Ao receber pedido de revisão de condicionante, o que a análise técnica deve registrar?',
    ['Somente a nova redação pretendida, sem registrar publicidade, motivação ou efeito atribuído ao pedido', 'O pedido, a motivação, a publicidade, o efeito atribuído e a decisão da autoridade competente', 'A suspensão automática de todas as condicionantes até a manifestação final da equipe de licenciamento'], 1,
    'O registro mantém rastreabilidade do pedido e da decisão no rito competente.',
    { sec: 'pop-section-097', quote: 'o técnico deve registrar o pedido, a motivação, a publicidade, o efeito atribuído e a decisão da autoridade competente' }],
  ['m12', 'Quando a compensação por impacto negativo não mitigável deve ser analisada?',
    ['Sempre que o empreendimento for classificado como PCH ou UHE, independentemente do impacto residual', 'Quando os estudos e a análise identificarem impacto ambiental negativo que não possa ser mitigado', 'Quando existir qualquer impacto ambiental, mesmo que as medidas propostas sejam suficientes para mitigá-lo'], 1,
    'Tipologia, potência ou simples existência de impacto não substituem a demonstração do impacto residual não mitigável.',
    { sec: 'pop-section-153', quote: 'somente deve ser analisada quando os estudos ambientais e a análise técnica identificarem impacto ambiental negativo não mitigável' }],
  ['m12', 'Por que o regime do art. 36 do SNUC não deve ser confundido com o procedimento do Decreto Estadual nº 7.150/2024?',
    ['Porque toda compensação estadual é facultativa e toda compensação federal é automaticamente obrigatória', 'Porque são mecanismos distintos e o analista precisa identificar previamente qual regime incide', 'Porque apenas um deles admite estudo ambiental e o outro depende exclusivamente da potência instalada'], 1,
    'O fundamento, o estudo e a destinação de cada regime precisam ser distinguidos antes do encaminhamento.',
    { sec: 'pop-section-154', quote: 'o analista deve identificar previamente qual regime incide, evitando tratar os dois mecanismos como uma única obrigação' }],
  ['m12', 'A Câmara do Decreto Estadual nº 7.150/2024 pode ser tratada como a mesma estrutura da compensação do art. 36 do SNUC?',
    ['Sim, porque toda Câmara de Compensação Ambiental possui idêntica competência e segue o mesmo fluxo', 'Não; a manifestação deve identificar o regime e encaminhar à instância competente correspondente', 'Sim, quando ainda não houver publicação de atas ou deliberações da estrutura criada no âmbito estadual'], 1,
    'Estruturas associadas a regimes diferentes não podem ser confundidas apenas pela semelhança do nome.',
    { sec: 'pop-section-156', quote: 'Essa Câmara não deve ser confundida com a estrutura utilizada para a compensação vinculada ao art. 36 do SNUC.' }],
  ['m12', 'Após a publicação do Decreto Estadual nº 7.150/2024, como descrever uma eventual falta de fluxo operacional?',
    ['Como ausência de regulamentação legal, recomendando aguardar indefinidamente a edição do primeiro decreto', 'Como pendência de operacionalização, fluxo interno ou deliberação, conforme a situação efetivamente confirmada', 'Como suspensão genérica de todas as compensações até que cada Câmara publique suas atas em página institucional'], 1,
    'A regulamentação existe; uma dificuldade operacional deve ser nomeada com precisão e preservada no histórico.',
    { sec: 'pop-section-158', quote: 'A regulamentação legal existe. Caso a unidade competente informe que o procedimento ainda não está operacionalizado, a situação deve ser descrita de forma precisa como pendência de operacionalização, definição de fluxo interno ou deliberação da Câmara Técnica, conforme o caso' }],
  ['m12', 'Ao tratar de compensação ambiental, a conclusão técnica pode limitar-se a copiar a legislação?',
    ['Sim, desde que a transcrição contenha todos os artigos citados no fundamento da compensação', 'Não; deve relacionar impacto, medidas, residual, regime, fase, atos existentes e providência', 'Sim, quando o cálculo ainda não foi produzido pela instância responsável pelo procedimento administrativo'], 1,
    'A conclusão precisa aplicar a norma aos elementos demonstrados no processo.',
    { sec: 'pop-section-159', quote: 'A conclusão não deve limitar-se a reproduzir a legislação.' }],
  ['m12', 'Enquanto um fluxo complementar não estiver confirmado, qual é o limite de atuação do analista?',
    ['Criar uma etapa por analogia para permitir que o processo avance até a regulamentação interna definitiva', 'Limitar-se às normas e aos atos formais do processo, sem criar etapas administrativas por analogia', 'Dispensar os requisitos vigentes até que todos os procedimentos internos estejam publicados na internet'], 1,
    'Incerteza procedimental deve ser registrada e validada, não preenchida por uma regra criada no caso.',
    { sec: 'pop-section-160', quote: 'o técnico deve limitar-se à redação expressa das normas e aos atos formalmente constantes do processo, sem criar etapas administrativas por analogia' }],

  // M13 — formatação e qualidade
  ['m13', 'Qual conteúdo mínimo diferencia o Relatório de Vistoria entre os produtos técnicos?',
    ['Somente data, equipe, lista de presença e fotografias gerais do empreendimento vistoriado', 'Objetivo, referências, pontos, coordenadas, registros, achados, limitações, consequência e encaminhamento', 'Apenas a conclusão de viabilidade, as condicionantes propostas e a aprovação da chefia responsável'], 1,
    'O relatório de campo precisa preservar o caminho entre o que foi observado e a consequência técnica.',
    { sec: 'pop-section-101', quote: 'Objetivo; data; equipe; documentos de referência; roteiro; pontos vistoriados; coordenadas; registros fotográficos; achados; limitações; consequência; encaminhamento.' }],
  ['m13', 'Por que não se deve combinar numeração automática com números digitados no mesmo título?',
    ['Porque isso impede inserir qualquer hiperlink para capítulos, anexos ou referências do documento', 'Porque a combinação gera duplicidade e pode produzir continuidade indevida na numeração', 'Porque os números digitados alteram automaticamente as margens e os campos de assinatura institucional'], 1,
    'Uma única forma de numeração mantém títulos, sumário e referências internos coerentes.',
    { sec: 'pop-section-102', quote: 'Não combinar numeração automática com números digitados no mesmo título, pois isso gera duplicidade e continuidade indevida.' }],
  ['m13', 'A cor pode ser o único meio de comunicar o status em uma tabela técnica?',
    ['Sim, quando a paleta possui contraste suficiente na tela usada pela equipe para revisar o documento', 'Não; o status precisa permanecer compreensível sem depender exclusivamente da cor', 'Sim, desde que a legenda explique no início do documento o significado de cada tom utilizado'], 1,
    'O documento deve preservar a informação em diferentes condições de leitura e impressão.',
    { sec: 'pop-section-104', quote: 'Não utilizar cor como único meio de comunicar status.' }],
  ['m13', 'Pode-se atribuir aprovação a uma pessoa ou unidade sem comprovação no processo?',
    ['Sim, quando a mesma pessoa aprovou documentos anteriores do empreendimento e continua na instituição', 'Não; campos de competência devem ser preservados e a aprovação precisa estar comprovada', 'Sim, desde que a indicação seja marcada como provisória e retirada somente depois da assinatura final'], 1,
    'A identificação de elaboração, revisão e aprovação faz parte da rastreabilidade do produto.',
    { sec: 'pop-section-106', quote: 'Não atribuir aprovação a pessoa ou unidade sem comprovação.' }],
  ['m13', 'O que o checklist de qualidade final exige sobre modalidade e suficiência documental?',
    ['Que sejam apresentadas em uma única frase para reduzir a possibilidade de divergência entre conclusões', 'Que a adequação da modalidade seja analisada separadamente da suficiência dos documentos', 'Que apenas a modalidade seja revisada, pois a presença dos arquivos já comprova a suficiência material'], 1,
    'A separação evita que um enquadramento correto seja confundido com documentação suficiente.',
    { sec: 'pop-section-109', quote: 'Adequação da modalidade separada da suficiência documental.' }],

  // M14 — modelos e anexos
  ['m14', 'Como deve ser usada a estrutura do modelo de Informação Técnica do Anexo B?',
    ['Como texto fixo que não admite ajuste de escopo, ordem ou conteúdo para o empreendimento analisado', 'Como estrutura adaptável ao caso concreto, preservando linguagem objetiva e institucional', 'Como substituta da análise técnica quando todos os campos formais forem corretamente preenchidos'], 1,
    'O modelo padroniza a estrutura, mas a análise continua vinculada ao caso concreto.',
    { sec: 'pop-section-111', quote: 'A estrutura abaixo deve ser adaptada ao caso concreto, mantendo linguagem objetiva e institucional.' }],
  ['m14', 'Qual conjunto pertence à identificação do modelo de Informação Técnica?',
    ['Empreendimento, empreendedor, município, corpo hídrico, bacia, tipologia, modalidade e protocolo', 'Somente nome do empreendimento, conclusão recomendada, condicionantes e assinatura do responsável', 'Estudo ambiental, programas, cronograma de obras, custo das medidas e manifestação dos intervenientes'], 0,
    'A identificação reúne os elementos necessários para localizar o objeto e o requerimento analisado.',
    { sec: 'pop-section-112', quote: 'Empreendimento: [nome]. Empreendedor: [razão social e CNPJ]. Município: [município]. Corpo hídrico: [nome]. Bacia: [nome]. Tipologia: [MCH, MGH, CGH, PCH ou UHE]. Modalidade requerida: [modalidade]. Protocolo: [número].' }],
  ['m14', 'O que o campo “Objeto” deve delimitar no modelo de Informação Técnica?',
    ['O requerimento, o empreendimento e a avaliação da suficiência documental e técnica apresentada', 'A decisão final da autoridade, incluindo assinatura, validade da licença e cronograma de fiscalização', 'A lista completa de normas, sem relacioná-las à modalidade ou à fase do processo em exame'], 0,
    'O objeto informa com precisão o que está sendo analisado e qual é o alcance daquela manifestação.',
    { sec: 'pop-section-113', quote: 'Trata-se de análise técnica do requerimento de [modalidade] para o empreendimento [nome], com vistas à avaliação da suficiência documental e técnica dos elementos apresentados.' }],
  ['m14', 'Quais elementos devem aparecer no histórico da Informação Técnica?',
    ['Somente a licença imediatamente anterior e o último documento juntado antes da análise atual', 'Licenças, Consulta Prévia, autorizações, transferências, outorga, atos, condicionantes e movimentações relevantes', 'Apenas os fatos favoráveis ao requerimento, deixando pendências e mudanças de titularidade para a conclusão'], 1,
    'O histórico seleciona movimentações que explicam a situação atual do processo.',
    { sec: 'pop-section-114', quote: 'Relatar licenças anteriores, Consulta Prévia, autorizações, transferências, outorga, atos setoriais, condicionantes e movimentações relevantes.' }],
  ['m14', 'Como selecionar a base legal indicada no modelo do Anexo B?',
    ['Pela norma mais recente disponível, sem considerar quando o processo começou ou qual fase está em análise', 'Conforme a data do protocolo, a fase do processo, a transição e os Termos de Referência pertinentes', 'Pelo conjunto de normas citado no parecer anterior, reproduzido integralmente para preservar uniformidade'], 1,
    'A base legal precisa estar conectada à situação temporal e processual analisada.',
    { sec: 'pop-section-115', quote: 'Indicar normas aplicáveis, regra de transição e Termos de Referência pertinentes, conforme data do protocolo e fase do processo.' }],
  ['m14', 'Quais componentes devem ser registrados na metodologia da Informação Técnica?',
    ['Arquivo, fase, tipologia, protocolo, norma, suficiência ou inconsistência, consequência e encaminhamento', 'Somente os nomes dos profissionais, os programas utilizados e o tempo dedicado à leitura de cada arquivo', 'A conclusão pretendida, seguida dos documentos escolhidos para confirmar o resultado definido previamente'], 0,
    'A metodologia documenta o caminho de análise entre entrada, critério, avaliação e providência.',
    { sec: 'pop-section-116', quote: 'Registrar que a análise considerou documento apresentado, fase, tipologia, data do protocolo, norma aplicável, suficiência ou inconsistência, consequência técnica e encaminhamento.' }],
  ['m14', 'Quais colunas formam a tabela de análise documental do modelo?',
    ['Documento, status, achado, consequência e encaminhamento', 'Documento, tamanho do arquivo, data de criação, autor e quantidade de páginas', 'Documento, custo estimado, prazo de contratação, equipe e situação financeira'], 0,
    'As colunas conectam cada documento à avaliação e à providência correspondente.',
    { sec: 'pop-section-117', quote: 'Inserir tabela com documento, status, achado, consequência e encaminhamento.' }],
  ['m14', 'Qual conjunto integra a análise técnica prevista no modelo do Anexo B?',
    ['Memorial, estudos, cartografia, temas ambientais, competência, atos externos e sistemas associados', 'Somente memorial, cadastro, procuração, comprovante de pagamento e certidão municipal atualizada', 'Apenas impactos do meio físico, pois flora, fauna e interfaces administrativas pertencem a documentos separados'], 0,
    'A análise técnica integra componentes ambientais, territoriais, administrativos e setoriais pertinentes ao caso.',
    { sec: 'pop-section-118', quote: 'Avaliar memorial, estudo ambiental, cartografia, APP, flora, fauna, recursos hídricos, Unidades de Conservação, APAs, Planos de Manejo, zoneamentos, bases geoespaciais oficiais, competência administrativa' }],
  ['m14', 'Como condicionantes ou pendências devem aparecer no modelo de Informação Técnica?',
    ['Como pedidos genéricos para que o empreendedor cumpra integralmente todas as normas ambientais aplicáveis', 'Como itens verificáveis ou fundamentados, relacionados à base normativa e à consequência técnica', 'Como transcrição completa do Termo de Referência, sem distinguir o que foi ou não apresentado no processo'], 1,
    'A redação deve tornar identificáveis o fundamento, a lacuna ou obrigação e seu efeito técnico.',
    { sec: 'pop-section-120', quote: 'Apresentar condicionantes verificáveis ou pendências com base normativa e consequência técnica.' }],
  ['m14', 'Quais saídas podem ser indicadas no campo “Encaminhamento” do modelo?',
    ['Deferimento, diligência, complementação, manifestação não favorável ou envio à unidade competente', 'Somente deferimento ou arquivamento definitivo, sem possibilidade de diligência ou análise especializada', 'Aprovação automática, suspensão informal ou transferência do processo diretamente ao empreendedor'], 0,
    'O encaminhamento deve corresponder à conclusão e ao tipo de providência necessária.',
    { sec: 'pop-section-121', quote: 'Indicar deferimento, diligência, complementação, manifestação não favorável ou envio a unidade competente.' }],
  ['m14', 'Na matriz de análise por documento, qual pergunta é obrigatória para o RIMA?',
    ['Se a síntese é fiel ao EIA e compreensível para a participação social', 'Se o RIMA substitui todos os anexos técnicos e os arquivos cartográficos do EIA', 'Se o documento apresenta projeto executivo suficiente para autorizar imediatamente a instalação'], 0,
    'A matriz verifica simultaneamente fidelidade técnica e comunicação acessível ao público.',
    { sec: 'pop-section-122', quote: 'A síntese é fiel ao EIA e compreensível para participação social?' }],

  // M16 — controles do ACT e RTAA
  ['m16', 'Qual é o objetivo do roteiro de controle dos processos federais delegados?',
    ['Criar um único modelo imutável de relatório, independente do ACT e da orientação anual do Ibama', 'Manter base única e rastreável para preparar formulário, apoio e protocolo com menos retrabalho', 'Transferir a obrigação institucional para o servidor responsável pelo preenchimento no fim do exercício'], 1,
    'O roteiro organiza evidências ao longo do ano e precisa ser adaptado ao instrumento específico.',
    { sec: 'pop-section-161', quote: 'O objetivo é manter uma base única de dados que permita preparar o formulário anual, eventual relatório textual complementar, documentos de apoio e protocolo de envio com rastreabilidade e menor retrabalho.' }],
  ['m16', 'O que deve ser registrado no campo “Objeto e fase” da ficha de controle do ACT?',
    ['Empreendimento, estruturas, sistemas associados e fases efetivamente abrangidos', 'Somente o título do acordo e o nome do servidor que acompanha o processo estadual', 'Todas as fases possíveis do licenciamento, mesmo quando o instrumento não as abrange'], 0,
    'A ficha precisa demonstrar o alcance material e processual real da delegação.',
    { sec: 'pop-section-168', quote: 'Empreendimento, estruturas, sistemas associados e fases efetivamente abrangidos.' }],
  ['m16', 'Que evidência o controle anual associa à entrega do RTAA?',
    ['Formulário ou meio vigente, anexos aplicáveis e comprovante ou protocolo', 'Somente uma cópia da licença mais recente emitida durante o ano de referência', 'Uma declaração interna sem recibo, formulário ou vínculo com o canal de envio'], 0,
    'A evidência permite comprovar conteúdo, canal e tempestividade da entrega anual.',
    { sec: 'pop-section-169', quote: 'Formulário ou meio vigente, anexos aplicáveis e comprovante ou protocolo' }],
  ['m16', 'A estrutura interna de preparação do RTAA substitui o ACT ou o formulário vigente?',
    ['Sim, porque consolida todos os campos observados no formulário eletrônico utilizado no exercício de 2026', 'Não; se houver divergência, prevalecem o instrumento aplicável e a orientação atual do Ibama', 'Sim, desde que a mesma estrutura tenha sido utilizada e aceita na entrega do exercício anterior'], 1,
    'A estrutura ajuda a organizar dados, mas permanece subordinada aos instrumentos vigentes.',
    { sec: 'pop-section-170', quote: 'Ele não substitui a Instrução Normativa IBAMA nº 08/2019, o ACT nem o formulário vigente do exercício.' }],
  ['m16', 'As janelas internas da rotina anual criam novos prazos jurídicos para o RTAA?',
    ['Sim, janeiro, fevereiro e março passam a ser etapas legais obrigatórias para todo órgão delegatário', 'Não; são recomendações de organização, e o prazo geral indicado permanece 31 de março', 'Sim, mas somente quando a equipe deixa de atualizar continuamente as movimentações do empreendimento'], 1,
    'A rotina distribui o trabalho interno sem alterar o prazo previsto no instrumento normativo.',
    { sec: 'pop-section-171', quote: 'A rotina abaixo é recomendação operacional interna e não cria novos prazos jurídicos. O único prazo geral indicado pela IN IBAMA nº 08/2019 para o RTAA é o encaminhamento até 31 de março.' }],
  ['m16', 'O exemplo de peticionamento da UHE Segredo em 2026 define os documentos obrigatórios para todos os RTAA?',
    ['Sim, formulário, relatório textual, licença e documentos técnicos devem acompanhar toda entrega futura', 'Não; a equipe só deve encaminhar o que for aplicável ao ACT e à orientação vigente', 'Sim, exceto quando o relatório anual não registrar nenhuma licença emitida no período de referência'], 1,
    'Um exemplo operacional demonstra uma possibilidade, mas não substitui a conferência do caso e do exercício.',
    { sec: 'pop-section-172', quote: 'isso não significa que a mesma composição seja obrigatória para todos os empreendimentos ou exercícios' }],
  ['m16', 'Depois do envio do RTAA, o que deve ser registrado no controle setorial?',
    ['Ano, data, canal, comprovante, protocolo, documentos enviados e eventual resposta do Ibama', 'Somente a data de envio e o nome do servidor que realizou o preenchimento do formulário', 'Apenas as pendências encerradas, excluindo do controle aquelas que seguem para o exercício seguinte'], 0,
    'O fechamento preserva a prova da entrega e mantém pendências acompanhadas até seu encerramento.',
    { sec: 'pop-section-173', quote: 'registrar no controle setorial o ano de referência, a data de envio, o canal utilizado, o comprovante do formulário quando aplicável, o número do protocolo ou recibo SEI/IBAMA quando houver peticionamento, os documentos encaminhados e eventual resposta ou solicitação do Ibama' }],

  // M14 — referências
  ['m14', 'Ao usar um Acordo de Cooperação Técnica como referência, o que precisa ser consultado?',
    ['O ACT específico, sua publicação e os aditivos aplicáveis ao empreendimento e à fase', 'Qualquer ACT anterior entre os mesmos órgãos, ainda que trate de outro empreendimento ou objeto', 'Somente a instrução normativa geral, sem conferir vigência, publicação ou alcance do acordo concreto'], 0,
    'A referência ao acordo precisa corresponder ao instrumento que efetivamente fundamenta a execução delegada.',
    { sec: 'pop-section-125', quote: 'Consultar o ACT específico, sua publicação e eventuais termos aditivos aplicáveis ao empreendimento e à fase analisada.' }],
  // M08 - Diagnostico Climatico e analise de programas ambientais, secoes que
  // entraram com o POP v1.9. Cada questao cita o trecho da propria secao.
  //
  // Os distratores sao deliberadamente do mesmo tamanho da resposta correta. A
  // primeira versao destas onze questoes tinha a correta como a alternativa
  // mais longa em todas elas, e o portao de validade editorial reprovou: quem
  // nao estudou acerta pelo comprimento, e a questao deixa de medir o objetivo.
  ['m08', 'A quais processos se aplica o Diagnóstico Climático da Portaria IAT nº 42/2022?',
    ['Aos empreendimentos submetidos a EIA/RIMA, sem extensão automática aos estudos simplificados', 'A todo processo de licenciamento de hidrelétrica, qualquer que seja a modalidade adotada pelo IAT', 'Somente aos empreendimentos com reservatório acima de cem hectares ou potência superior a 10 MW'], 0,
    'A incidência acompanha a exigibilidade do EIA. Estender a DLAM, LAC, LAS, RAS, RDPA ou PCA exige fundamento próprio.',
    { sec: 'pop-section-174', quote: 'A incidência decorre da exigibilidade do EIA e não deve ser estendida automaticamente a DLAM, LAC, LAS, RAS, RDPA, PCA ou outros estudos simplificados sem fundamento específico em norma, TR, condicionante válida ou decisão técnica motivada.' }],

  ['m08', 'Ao analisar o Diagnóstico Climático de uma hidrelétrica, o que o técnico não deve presumir?',
    ['Nem emissão nula nem emissão elevada, avaliando fontes, remoções e vulnerabilidades do caso concreto', 'Que a emissão é nula, porque a geração hidrelétrica é fonte renovável e substitui térmicas fósseis', 'Que a emissão é elevada, porque todo reservatório alaga biomassa e passa a emitir metano na operação'], 0,
    'O POP recusa as duas presunções e manda avaliar o caso concreto.',
    { sec: 'pop-section-174', quote: 'Para hidrelétricas, não se deve presumir emissão nula nem elevada.' }],

  ['m08', 'Antes de avaliar o mérito de um programa ambiental, que distinção o técnico precisa fazer?',
    ['Entre o status declarado pelo empreendedor e o status validado pelo IAT ou pela área competente', 'Entre programas previstos no PBA e programas previstos no PCA, descartando os que não constem do PBA', 'Entre relatórios assinados por consultoria contratada e relatórios assinados pelo próprio empreendedor'], 0,
    'Declarar execução não é o mesmo que ter execução validada, e a análise precisa separar as duas coisas antes de concluir.',
    { sec: 'pop-section-175', quote: 'O status declarado pelo empreendedor deve ser distinguido do status validado pelo IAT ou pela área competente.' }],

  ['m08', 'A base jurídica de um programa ambiental é encontrada onde?',
    ['Na combinação entre o regime geral, a licença e suas condicionantes, o plano aprovado e a legislação do tema', 'Exclusivamente na instrução normativa que disciplina o licenciamento ambiental da tipologia do empreendimento', 'No termo de referência do estudo ambiental, que funciona como fonte única e suficiente da obrigação'], 0,
    'A obrigação não nasce de uma norma só: ela combina regime, licença, plano aprovado e legislação do tema monitorado.',
    { sec: 'pop-section-176', quote: 'A base jurídica de um programa ambiental decorre da combinação entre o regime geral do licenciamento, a licença e suas condicionantes, o estudo ou plano aprovado e a legislação material do tema monitorado.' }],

  ['m08', 'Como identificar de que trata um programa quando a denominação varia entre PCA, RDPA e PBA?',
    ['Pela função ambiental que ele exerce, e não apenas pelo título que recebeu', 'Pelo nome adotado na licença ambiental, que prevalece sobre o conteúdo do programa', 'Pela ordem em que o programa aparece listado no plano aprovado para o empreendimento'], 0,
    'O título muda de empreendedor para empreendedor. A função ambiental é o que permite comparar.',
    { sec: 'pop-section-177', quote: 'O técnico deve analisar a função ambiental exercida e não apenas o título.' }],

  ['m08', 'Ao comparar relatórios sucessivos, o que fazer com grandezas de naturezas diferentes?',
    ['Não somar massa, volume e unidades em um total único sem metodologia demonstrada', 'Converter tudo para quilogramas, adotando os fatores médios de referência do setor elétrico', 'Somar os valores e registrar o resultado como total consolidado do período de referência'], 0,
    'Somar o que não é somável produz um número que parece resultado e não é.',
    { sec: 'pop-section-178', quote: 'Não somar massa, volume e unidades em um único total sem metodologia tecnicamente demonstrada.' }],

  ['m08', 'Um indicador apresentado sem meta e sem referência temporal demonstra efetividade?',
    ['Não, porque valor isolado sem referência temporal ou meta não demonstra efetividade', 'Sim, desde que o valor esteja assinado por responsável técnico com ART recolhida no período', 'Sim, desde que o mesmo valor apareça em dois relatórios seguidos do mesmo programa ambiental'], 0,
    'Indicador precisa de unidade, meta ou referência, periodicidade e interpretação para dizer alguma coisa.',
    { sec: 'pop-section-179', quote: 'Valor isolado sem referência temporal ou meta não demonstra, por si só, efetividade.' }],

  ['m08', 'Quando o mérito depende de unidade especializada, o que cabe à Informação Técnica de Apoio?',
    ['Registrar o que foi verificado e delimitar o ponto que permanece pendente de validação', 'Concluir sobre o mérito assim mesmo, já que a análise documental alcança todos os temas do programa', 'Suspender a análise inteira do relatório até que a unidade especializada se manifeste nos autos'], 0,
    'A informação de apoio avalia coerência, execução documental e continuidade, e diz até onde foi.',
    { sec: 'pop-section-180', quote: 'A Informação Técnica de Apoio pode avaliar a coerência, a execução documental e a continuidade dos programas, mas não deve substituir manifestação de unidade especializada quando o mérito depender de atribuição específica.' }],

  ['m08', 'O que a Informação Técnica de Apoio sobre programas precisa permitir identificar?',
    ['O apresentado, o ocorrido no período, o que mudou desde o relatório anterior e a providência que falta', 'A lista completa dos documentos protocolados no período, com número de páginas e data de cada peça', 'A pontuação atribuída a cada programa em escala comparativa entre os empreendimentos da mesma bacia'], 0,
    'A estrutura existe para responder essas quatro perguntas, e é por isso que a comparação entre períodos é obrigatória.',
    { sec: 'pop-section-181', quote: 'a Informação Técnica de Apoio deve permitir ao leitor identificar o que foi apresentado, o que ocorreu no período, o que mudou em relação ao relatório anterior e qual providência ainda é necessária' }],

  ['m08', 'Programa executado, mas com inconsistência de redação no relatório. Qual o encaminhamento?',
    ['Solicitar retificação ou esclarecimento, sem equiparar a inconsistência à falta de execução', 'Concluir pela não execução do programa no período até que o relatório seja integralmente refeito', 'Aceitar o relatório como está, já que a execução material do programa foi demonstrada por evidência'], 0,
    'Há execução material. O problema está na série, na redação ou nas unidades, e é isso que se corrige.',
    { sec: 'pop-section-182', quote: 'Solicitar retificação ou esclarecimento sem equiparar a inconsistência' }],

  ['m08', 'Cercamento, retirada de exótica e preparação de área equivalem a restauração implantada?',
    ['Não, e confundir as duas coisas está entre os erros recorrentes que o POP evita', 'Sim, porque são etapas expressamente previstas no cronograma do programa de restauração aprovado', 'Sim, desde que estejam registradas em fotografia datada e georreferenciada no relatório do período'], 0,
    'Preparação não é execução. A restauração implantada exige resultado monitorado.',
    { sec: 'pop-section-183', quote: 'Confundir preparação de área, cercamento ou retirada de exótica com restauração efetivamente implantada e monitorada.' }],
];
