// Ampliacao do banco de questoes: nenhum modulo abaixo de oito perguntas.
//
// Por que este arquivo existe. A prontidao passou a exigir 80% na avaliacao do
// modulo. Com quatro questoes, 80% vira 4/4: margem de erro zero, e oito dos
// dezessete modulos estavam nessa situacao. Com oito questoes o corte cai para
// 7/8, exigente sem ser tudo ou nada, e a avaliacao passa a cobrir mais do
// capitulo.
//
// Formato de tupla, igual ao banco original de courseData.js:
//   [trilha, enunciado, [alternativas], indiceDaCorreta, explicacao, {sec, quote}]
// O par {sec, quote} liga a questao a secao do POP e ao trecho que a sustenta.
// O trecho precisa ser literal: tools/check-questoes.mjs falha se nao for.

export const QUESTOES_EXTRA = [
  // ---------- M00 Orientacao, escopo e controle documental ----------
  ['m00', 'Sem elemento suficiente para concluir, o que o POP determina ao técnico?',
    ['Concluir pelo indeferimento, por precaução', 'Registrar a limitação de forma explícita e proporcional', 'Aguardar sem registrar até que o empreendedor se manifeste'], 1,
    'A limitação registrada protege a decisão e quem decide: ela mostra o que não pôde ser verificado e por quê, em vez de esconder a lacuna numa conclusão.',
    { sec: 'pop-section-003', quote: 'registrar a limitação de forma explícita e proporcional' }],
  ['m00', 'De onde deve decorrer uma exigência documental feita ao empreendedor?',
    ['Do próprio POP e das práticas da equipe, desde que a exigência pareça útil à análise e seja comunicada em diligência única', 'Da norma aplicável, do Termo de Referência, do SGA, de condicionante anterior, de fato novo ou de inconsistência', 'Da lista usada em processo semelhante, ainda que não haja norma, TR, condicionante, fato novo ou inconsistência específica no caso'], 1,
    'O POP organiza o método e não é fundamento autônomo. Toda exigência precisa apontar a fonte que a sustenta.',
    { sec: 'pop-section-003', quote: 'A exigência deve decorrer da norma aplicável, do Termo de Referência pertinente' }],
  ['m00', 'Quais tipologias estão no escopo deste POP?',
    ['Somente PCH e UHE', 'MCH, MGH, CGH, PCH, UHE e sistemas associados', 'Apenas empreendimentos sujeitos a EIA/RIMA'], 1,
    'O escopo cobre toda a faixa de porte, das centrais menores às usinas, mais os sistemas associados do empreendimento.',
    { sec: 'pop-section-003', quote: 'MCH, MGH, CGH, PCH, UHE e sistemas associados no Estado do Paraná' }],
  ['m00', 'O que o POP busca preservar ao padronizar a análise?',
    ['A uniformidade da conclusão, para que casos parecidos terminem igual', 'A proporcionalidade da análise por fase, o rigor técnico e a rastreabilidade documental', 'A rapidez do trâmite acima dos demais critérios'], 1,
    'Padronizar o método não é padronizar o resultado: cada fase recebe a profundidade que lhe cabe, com registro que permite auditar o caminho.',
    { sec: 'pop-section-003', quote: 'preservando a proporcionalidade da análise por fase' }],

  // ---------- M01 Papeis, normas, definicoes e metodo ----------
  ['m01', 'Na ordem operacional de consulta, qual é a posição do Termo de Referência frente à lei?',
    ['O TR prevalece sobre a lei quando for mais específico para a tipologia e tiver publicação posterior', 'O TR detalha a instrução do caso, mas não prevalece sobre lei ou regulamento', 'TR e lei têm a mesma força na instrução, cabendo ao analista aplicar a regra mais recente'], 1,
    'A ordem de consulta não equipara atos de natureza distinta: TR, condicionantes e orientações internas instruem o caso concreto, sem se sobrepor à norma.',
    { sec: 'pop-section-005', quote: 'Termos de Referência, condicionantes e orientações internas não prevalecem sobre lei ou regulamento' }],
  ['m01', 'Qual critério de potência o Decreto Federal nº 8.437/2015 associa à competência federal?',
    ['Capacidade instalada igual ou superior a 100 MW', 'Capacidade instalada igual ou superior a 300 MW', 'Qualquer UHE, independentemente da potência'], 1,
    'O critério de 300 MW é um dos caminhos para a competência federal, que também pode decorrer de outros critérios da LC 140/2011 ou de situação jurídica específica.',
    { sec: 'pop-section-132', quote: 'licenciamento de usinas hidrelétricas com capacidade instalada igual ou superior a 300 MW' }],
  ['m01', 'Diante de dúvida relevante sobre alcance normativo ainda não firmado, o técnico deve:',
    ['Adotar a interpretação que a equipe considerar mais segura no caso e seguir com a análise', 'Registrar a pendência como Pendente de validação, sem criar solução normativa própria', 'Indeferir o pedido até que a dúvida seja resolvida'], 1,
    'Criar regra própria transfere para o analista uma competência que não é dele. O registro da pendência mantém o processo rastreável enquanto a definição não vem.',
    { sec: 'pop-section-008', quote: 'registrar a pendência como Pendente de validação, sem criar solução normativa própria' }],

  // ---------- M02 Fluxo geral, recebimento e triagem ----------
  ['m02', 'Qual é o objetivo declarado do fluxo geral de análise?',
    ['Acelerar o trâmite reduzindo etapas', 'Impedir que a análise comece pela conclusão', 'Uniformizar o resultado entre analistas diferentes'], 1,
    'A conclusão é resultado da compatibilização documental e técnica, nunca o ponto de partida da leitura.',
    { sec: 'pop-section-015', quote: 'O objetivo é impedir que a análise comece pela conclusão.' }],
  ['m02', 'Um ponto isolado em mapa é suficiente para delimitar o empreendimento?',
    ['Sim, quando o ponto indica com precisão a posição do eixo da barragem', 'Não; ponto isolado não delimita empreendimento hidrelétrico complexo', 'Sim, desde que acompanhado de memorial descritivo do arranjo'], 1,
    'Sem poligonais não há como analisar APP, supressão e interferências: a delimitação espacial é condição da análise, não detalhe cartográfico.',
    { sec: 'pop-section-019', quote: 'Ponto isolado em mapa não delimita empreendimento hidrelétrico complexo.' }],
  ['m02', 'Sobre o que deve incidir a triagem locacional e territorial em bases oficiais?',
    ['Somente sobre o ponto do barramento', 'Sobre o arranjo integral do empreendimento', 'Apenas sobre a área do reservatório'], 1,
    'A triagem alcança o arranjo inteiro porque a restrição territorial pode incidir sobre qualquer estrutura, não só sobre a barragem.',
    { sec: 'pop-section-018', quote: 'Executar triagem locacional e territorial do arranjo integral em bases oficiais' }],

  // ---------- M03 Enquadramento e Consulta Previa ----------
  ['m03', 'Para quais empreendimentos a Consulta Prévia é obrigatória?',
    ['Para toda CGH, qualquer que seja a potência instalada declarada', 'Para CGH com potência instalada igual ou superior a 1 MW, PCH e UHE', 'Somente para UHE, por causa do porte do reservatório'], 1,
    'Abaixo de 1 MW a CGH não tem Consulta Prévia obrigatória, mas o empreendedor pode buscá-la como orientação.',
    { sec: 'pop-section-024', quote: 'É obrigatória para CGH com potência instalada igual ou superior a 1 MW, PCH e UHE.' }],
  ['m03', 'A Consulta Prévia chegou com mapa da ADA e Memorial Descritivo, mas sem o arquivo digital do arranjo. Qual providência completa a entrada mínima?',
    ['Exigir EIA/RIMA completo antes de qualquer orientação', 'Solicitar o arranjo em KML ou KMZ', 'Prosseguir apenas com o requerimento assinado e a taxa'], 1,
    'O KML ou KMZ completa o conjunto mínimo necessário para localizar e caracterizar o arranjo, sem antecipar estudos próprios de fases posteriores.',
    { sec: 'pop-section-025', quote: 'mapa da delimitação da ADA, mapa digital do arranjo em formato KML ou KMZ e Memorial Descritivo' }],
  ['m03', 'O requerente apresenta o registro setorial da ANEEL como prova suficiente do enquadramento ambiental estadual. Como analisar essa alegação?',
    ['Usar o ato da ANEEL para definir a modalidade ambiental', 'Separar as finalidades e conferir cada enquadramento no respectivo regime', 'Dispensar o ato setorial porque o IAT já fez o enquadramento ambiental'], 1,
    'A classificação ambiental serve ao licenciamento estadual; o regime setorial serve ao aproveitamento do potencial hidráulico e aos atos do setor elétrico.',
    { sec: 'pop-section-023', quote: 'Uma classificação não substitui a outra.' }],

  // ---------- M04 DLAM, LAC e LAS ----------
  ['m04', 'A localização em Unidade de Conservação, inclusive APA, afasta a DLAM no regime estadual indicado pelo POP?',
    ['Não; a anuência do gestor torna a dispensa cabível em qualquer UC de Uso Sustentável', 'Sim; o art. 56, I, do Decreto Estadual nº 9.541/2025 afasta a DLAM em UC, inclusive APA', 'Não; a ausência de supressão e intervenção em APP basta para manter a dispensa'], 1,
    'O critério estadual citado afasta a DLAM em UC, inclusive APA; depois disso, define-se o procedimento aplicável sem presumir automaticamente uma modalidade substitutiva.',
    { sec: 'pop-section-029', quote: 'a DLAM não é cabível quando o empreendimento estiver localizado em Unidade de Conservação, inclusive APA' }],
  ['m04', 'Apesar da exceção federal para APA, o critério estadual mais restritivo indicado pelo POP continua impedindo a LAC em UC, inclusive APA?',
    ['Não; a exceção federal afasta automaticamente o critério estadual mais restritivo', 'Sim; o art. 64, I, e, mantém o impedimento à LAC em UC, inclusive APA', 'Não; a omissão do Plano de Manejo restabelece a LAC independentemente da regra estadual'], 1,
    'A exceção federal existe, mas não elimina por si só o critério estadual mais restritivo: em UC, inclusive APA, não se conclui pela LAC.',
    { sec: 'pop-section-030', quote: 'o art. 64, I, e, do Decreto Estadual nº 9.541/2025 impede a LAC em Unidade de Conservação, inclusive APA' }],
  ['m04', 'Quais critérios a IN IAT nº 09/2025 prevê para LAC de CGH?',
    ['Potência até 3 MW e alagamento inferior a 13 ha, ainda que haja supressão de vegetação nativa na área do arranjo', 'Potência de até 1 MW, alagamento inferior a 5 ha, IDA menor que 3 e ausência de necessidade de autorização de supressão', 'Qualquer potência e alagamento, desde que o empreendedor firme termo de compromisso de ajustamento de conduta'], 1,
    'Os quatro critérios formam apenas o enquadramento inicial. A modalidade ainda depende dos critérios gerais e da compatibilidade territorial; em UC, inclusive APA, o POP orienta não concluir pela LAC.',
    { sec: 'pop-section-030', quote: 'Para CGH, a IN prevê LAC para potência de até 1 MW, alagamento inferior a 5 ha, IDA menor que 3 e ausência de necessidade de autorização de supressão' }],
  ['m04', 'No rito da LAS, a supressão de vegetação continua exigindo análise de flora, fauna, APP e autorização florestal?',
    ['Não; o rito simplificado absorve a análise e a autorização florestal', 'Sim; a disciplina material da supressão permanece aplicável', 'Não; área inferior a um hectare em estágio inicial fica dispensada dessas análises'], 1,
    'Simplificar o rito não simplifica o dever técnico: a disciplina material da supressão permanece integralmente aplicável.',
    { sec: 'pop-section-031', quote: 'A existência de supressão não autoriza dispensar análise de flora, fauna, APP ou autorização florestal.' }],

  // ---------- M05 Licenciamento trifasico ----------
  ['m05', 'Qual gatilho numérico específico para PCH aparece no conjunto de hipóteses de EIA e RIMA do POP?',
    ['Qualquer potência, sempre que houver outorga vigente', 'Potência acima de 10 MW ou alagamento superior a 100 ha', 'Somente alagamento superior a 1.000 ha'], 1,
    'O gatilho numérico não é uma lista exaustiva. O mesmo trecho também alcança UHE e empreendimento inicialmente simplificado que o IAT considere potencialmente impactante.',
    { sec: 'pop-section-034', quote: 'às PCHs com potência acima de 10 MW ou alagamento superior a 100 ha e aos empreendimentos inicialmente simplificados que o IAT considere potencialmente impactantes' }],
  ['m05', 'Por quanto tempo o EIA e o RIMA devem ficar disponíveis ao público antes da audiência?',
    ['No mínimo 15 dias', 'No mínimo 45 dias', 'No mínimo 90 dias'], 1,
    'A disponibilização prévia é condição da participação: sem prazo de leitura, a audiência perde a função instrutória.',
    { sec: 'pop-section-040', quote: 'devem permanecer disponíveis ao público por, no mínimo, 45 dias antes da audiência' }],
  ['m05', 'O que a Licença de Operação verifica em primeiro lugar?',
    ['Se a concepção do empreendimento licenciado continua viável', 'Se o empreendimento foi implantado conforme a licença e o projeto aprovado', 'Se o cronograma físico da obra foi integralmente cumprido no prazo previsto'], 1,
    'A LO confronta o executado com o licenciado, verifica o atendimento das condicionantes e a compatibilidade da operação projetada.',
    { sec: 'pop-section-038', quote: 'verificar se o empreendimento foi implantado conforme licença e projeto aprovado' }],

  // ---------- M06 AA, renovacao, regularizacao, transferencia ----------
  ['m06', 'Quais hipóteses de Autorização Ambiental a IN IAT nº 09/2025 prevê expressamente?',
    ['Qualquer intervenção considerada de pequeno porte pela equipe', 'Enchimento de reservatório e testes de comissionamento', 'Supressão de vegetação em APP'], 1,
    'A AA tem objeto delimitado e não substitui licença principal, Autorização Florestal, outorga nem manifestação de interveniente.',
    { sec: 'pop-section-041', quote: 'possui aplicação expressa para enchimento de reservatório e testes de comissionamento' }],
  ['m06', 'Qual prazo a Lei Federal nº 15.190/2025 estabelece para decidir o pedido de alteração de titularidade?',
    ['Até 15 dias, com possibilidade de rever condicionantes mesmo sem alteração dos impactos do empreendimento', 'Até 30 dias, sem majorar condicionantes quando não houver incremento de impactos', 'Até 120 dias, prorrogáveis uma vez, aplicando-se novo enquadramento ambiental à transferência'], 1,
    'A transferência é ato administrativo próprio: exige comprovação de poderes, assunção de condicionantes e compatibilidade com outorga e ANEEL.',
    { sec: 'pop-section-048', quote: 'o pedido de alteração de titularidade deve ser decidido em até 30 dias e não pode resultar em majoração de condicionantes' }],
  ['m06', 'Como se calcula o porte na ampliação definitiva de um empreendimento?',
    ['Considerando apenas a estrutura nova que se pretende implantar', 'Considerando o somatório da estrutura existente e da pretendida', 'Considerando a maior das duas estruturas'], 1,
    'O somatório evita que ampliações sucessivas mantenham artificialmente o empreendimento em faixa de menor exigência.',
    { sec: 'pop-section-050', quote: 'A ampliação definitiva considera o somatório da estrutura existente e da estrutura pretendida.' }],

  // ---------- M07 Sistemas associados e seguranca de barragens ----------
  ['m07', 'A incidência da Política Nacional de Segurança de Barragens decorre da classificação do empreendimento?',
    ['Sim; toda estrutura associada a PCH ou UHE integra automaticamente a PNSB, independentemente dos critérios legais do barramento', 'Não; a incidência se verifica pelas características e critérios legais da estrutura', 'Sim, mas somente para UHE ou para barragens vinculadas a empreendimentos com licenciamento trifásico'], 1,
    'A sigla do empreendimento não decide a incidência: o que importa são as características do barramento e os critérios da lei.',
    { sec: 'pop-section-054', quote: 'A incidência da PNSB não decorre apenas da classificação do empreendimento como PCH ou UHE' }],
  ['m07', 'Para estruturas fiscalizadas pela ANEEL, qual norma o POP manda consultar?',
    ['Resolução Normativa ANEEL nº 875/2020, sobre outorga', 'Resolução Normativa ANEEL nº 1.064, de 2 de maio de 2023', 'Resolução CONAMA nº 428/2010, sobre zona de amortecimento'], 1,
    'A ResNorm 875/2020 trata dos procedimentos setoriais de PCH e UHE; a 1.064/2023 é a referência de segurança de barragens sob fiscalização da ANEEL.',
    { sec: 'pop-section-054', quote: 'Resolução Normativa ANEEL nº 1.064, de 2 de maio de 2023' }],
  ['m07', 'O que a decisão deve registrar ao tratar sistemas associados e áreas de apoio?',
    ['Apenas a área total ocupada e a distância até o empreendimento principal em análise', 'Vínculo funcional, área de intervenção, titularidade, competência e impactos cumulativos', 'Somente a titularidade do empreendedor e a fase em curso'], 1,
    'Esse registro é o que permite justificar a análise conjunta ou separada de linhas, subestações, canteiros, jazidas e bota-fora.',
    { sec: 'pop-section-051', quote: 'A decisão deve registrar o vínculo funcional, a área de intervenção, a titularidade, a competência, os impactos cumulativos' }],
  ['m07', 'O que a manifestação do licenciamento não deve declarar sobre a barragem?',
    ['A consequência ambiental identificada, quando vinculada às evidências do processo e aos limites da competência da unidade', 'Estabilidade, segurança estrutural ou atendimento definitivo de obrigação de outro órgão', 'Os limites da própria análise e a indicação de que a validação estrutural pertence ao órgão fiscalizador competente'], 1,
    'Declarar segurança estrutural extrapola a atribuição da unidade e cria aparência de validação que o órgão fiscalizador não deu.',
    { sec: 'pop-section-056', quote: 'sem declarar estabilidade, segurança estrutural ou atendimento definitivo de obrigação cuja validação pertença a outro órgão' }],

  // ---------- M08 Memorial e estudos ambientais ----------
  ['m08', 'Memorial Descritivo e estudo ambiental apresentam arranjos de épocas diferentes. Qual providência preserva a coerência da análise?',
    ['Adotar o estudo antigo como correção automática do Memorial', 'Atualizar e compatibilizar os dois documentos, respeitando a função de cada um', 'Usar o Memorial como substituto da análise de impactos'], 1,
    'Memorial e estudo têm funções distintas: um caracteriza o empreendimento, o outro avalia impactos; a compatibilização precisa preservar ambos.',
    { sec: 'pop-section-060', quote: 'Estudo ambiental antigo não corrige memorial desatualizado' }],
  ['m08', 'O que caracteriza um RDPA suficiente?',
    ['Reproduzir o diagnóstico apresentado no RAS com um nível maior de detalhe', 'Transformar as propostas básicas em programas executáveis e verificáveis', 'Apresentar apenas o cronograma de execução dos programas'], 1,
    'O programa precisa permitir acompanhar execução, resultado e efetividade; copiar o RAS não cumpre essa função.',
    { sec: 'pop-section-063', quote: 'Não basta reproduzir o diagnóstico ou copiar o texto do RAS.' }],
  ['m08', 'Como pode ser afastado um item do Termo de Referência considerado não aplicável?',
    ['Por simples omissão no estudo', 'Somente mediante justificativa técnica', 'Por acordo verbal com o analista'], 1,
    'O TR estabelece conteúdo mínimo e admite aprofundamento justificado; afastar item exige demonstração, não silêncio.',
    { sec: 'pop-section-058', quote: 'Item não aplicável somente pode ser afastado mediante justificativa técnica.' }],

  // ---------- M09 PACUERA ----------
  ['m09', 'Com que periodicidade o TR PACUERA 2026 determina a revisão do plano?',
    ['A cada 5 anos', 'A cada 10 anos', 'Somente na renovação da licença de operação'], 1,
    'O plano também deve ser protocolado simultaneamente ao PBA ou ao RDPA, conforme a licença e o estudo aplicáveis.',
    { sec: 'pop-section-068', quote: 'revisto obrigatoriamente a cada 10 anos' }],
  ['m09', 'Qual escala preferencial o TR estabelece para os produtos temáticos do PACUERA?',
    ['Até 1:100.000, salvo quando o diagnóstico municipal exigir representação em escala mais detalhada', 'Até 1:25.000, admitida exceção tecnicamente justificada', 'Até 1:250.000, desde que a base vetorial contenha tabela de atributos e controle de topologia'], 1,
    'A escala acompanha a exigência de base vetorial única, tabela de atributos, controle de topologia e referência geodésica.',
    { sec: 'pop-section-070', quote: 'A escala preferencial dos produtos temáticos é de até 1:25.000' }],
  ['m09', 'O zoneamento do PACUERA pode autorizar uso vedado pela Unidade de Conservação incidente?',
    ['Sim, o PACUERA é mais específico para o entorno do reservatório', 'Não; ele deve ser compatibilizado com o ato de criação e o Plano de Manejo vigente', 'Sim, mediante anuência do empreendedor'], 1,
    'O PACUERA organiza o uso do entorno dentro do que a norma territorial permite; ele não cria permissão que a UC veda.',
    { sec: 'pop-section-072', quote: 'O PACUERA não pode autorizar uso territorial vedado ou incompatível com a Unidade de Conservação.' }],

  // ---------- M10 Cartografia, APP, flora, fauna e recursos hidricos ----------
  ['m10', 'O que o material cartográfico deve conter, conforme a fase e a complexidade do arranjo?',
    ['Escala, legenda, coordenadas centrais e assinatura, ficando projeção e datum restritos aos arquivos vetoriais', 'Título, legenda, escala, orientação, projeção, datum, data e responsável técnico', 'Coordenadas do barramento, delimitação do reservatório e data, ainda que sem orientação ou responsável técnico'], 1,
    'Sem esses elementos não se consegue localizar, delimitar nem quantificar impactos, que é a função da peça cartográfica.',
    { sec: 'pop-section-076', quote: 'título, legenda, escala, orientação, projeção, datum, data, responsável técnico' }],
  ['m10', 'Como tratar a ausência de outorga vigente ou equivalente?',
    ['Como pendência de baixa gravidade, sanável depois da licença', 'Como possível pendência crítica para instalação, operação e renovação', 'Como assunto alheio ao licenciamento ambiental'], 1,
    'A gravidade se define pela consequência: sem outorga não há como compatibilizar vazões, TVR, usos múltiplos e operação.',
    { sec: 'pop-section-080', quote: 'Ausência de outorga vigente ou equivalente pode ser pendência crítica' }],
  ['m10', 'Havendo divergência entre a camada geográfica, o ato de criação e o Plano de Manejo, o técnico deve:',
    ['Corrigir a geometria conforme sua leitura do ato legal', 'Classificar como Pendente de validação e consultar a unidade competente', 'Adotar sempre a camada do GeoPR, por ser oficial'], 1,
    'A própria página de Planos de Manejo informa que a camada de zoneamento está em atualização, o que reforça não corrigir geometria por interpretação própria.',
    { sec: 'pop-section-134', quote: 'não corrigir a geometria por interpretação própria' }],
  ['m10', 'Qual norma o POP indica para os estudos de fauna?',
    ['As IN IAT nº 01/2023 e nº 02/2023, mantidas como regra geral vigente para novos estudos de fauna', 'Portaria IAT nº 012, de 10 de janeiro de 2024, com atenção ao Anexo II', 'Portaria IAT nº 012/2024, mas sem aplicar o Anexo II às hidrelétricas, por ser roteiro facultativo'], 1,
    'As IN IAT nº 01/2023 e nº 02/2023 permanecem apenas como contexto histórico revogado; o Anexo II trata especificamente de hidrelétricas.',
    { sec: 'pop-section-079', quote: 'aplicar a Portaria IAT nº 012, de 10 de janeiro de 2024' }],

  // ---------- M11 ANEEL, IPHAN, municipio e vistoria ----------
  ['m11', 'Já existindo processo IPHAN em andamento para o empreendimento, o que não se deve fazer?',
    ['Acompanhar o processo administrativo no SEI', 'Abrir nova Ficha de Caracterização da Atividade para o mesmo empreendimento', 'Encaminhar os documentos posteriores por meio do sistema de Protocolo Digital'], 1,
    'O SAIP é usado para a FCA; a partir dela o processo segue no SEI, e abrir nova ficha duplica a instrução.',
    { sec: 'pop-section-083', quote: 'Não abrir nova FCA para o mesmo empreendimento quando já houver processo IPHAN em andamento.' }],
  ['m11', 'Qual é o gatilho de entorno para ciência ao órgão gestor da UC em processos não sujeitos a EIA/RIMA?',
    ['Até quinhentos metros da UC, independentemente da existência de zona de amortecimento ou de impacto direto', 'Até dois mil metros, quando a zona de amortecimento não tenha sido estabelecida', 'Até dez quilômetros da UC, sempre que o empreendimento estiver sujeito a licenciamento estadual simplificado'], 1,
    'O gatilho de dois mil metros não alcança Áreas Urbanas Consolidadas, APAs e RPPNs, mas a ciência permanece quando houver impacto direto.',
    { sec: 'pop-section-141', quote: 'no entorno de até dois mil metros de UC cuja zona de amortecimento não tenha sido estabelecida' }],
  ['m11', 'Qual é o limite do relatório de vistoria técnica?',
    ['Ele pode substituir o estudo técnico quando a equipe for multidisciplinar', 'Ele registra fatos observados e não conclui além do observado', 'Ele deve concluir sobre a viabilidade do empreendimento'], 1,
    'A vistoria é planejada a partir dos pontos críticos do processo e alimenta a análise; ela não faz as vezes do estudo.',
    { sec: 'pop-section-087', quote: 'O relatório de vistoria deve registrar fatos observados, não substituir estudo técnico nem concluir além do observado.' }],

  // ---------- M12 Suficiencia, pendencias, condicionantes e conclusao ----------
  ['m12', 'Qual destas é uma condicionante que deve ser evitada?',
    ['A que fixa prazo e forma de comprovação para o empreendedor', 'A que transfere ao empreendedor competência decisória do órgão ambiental', 'A que decorre de impacto já avaliado e aceito no estudo ambiental'], 1,
    'A condicionante organiza obrigação do empreendedor; ela não pode deslocar para ele a decisão que cabe ao órgão.',
    { sec: 'pop-section-095', quote: 'Condicionante que transfere ao empreendedor competência decisória do órgão ambiental.' }],

  // ---------- M13 Formatacao, qualidade e rastreabilidade ----------
  ['m13', 'Ao editar um documento técnico, o que a regra de precedência determina?',
    ['Converter o arquivo para um modelo simplificado e padronizado pelo próprio órgão licenciador', 'Editar o original ou cópia fiel, preservando cabeçalho, rodapé, margens e campos institucionais', 'Recriar o documento a partir do texto extraído automaticamente do arquivo recebido'], 1,
    'A identidade visual do documento de origem faz parte da sua validade formal e da rastreabilidade institucional.',
    { sec: 'pop-section-100', quote: 'Não substituir documento formatado por arquivo simplificado.' }],
  ['m13', 'Como devem ser apresentadas as coordenadas em um documento técnico do IAT?',
    ['Apenas com latitude e longitude em graus decimais', 'Indicando sistema, zona, datum e unidade', 'No formato usado pelo empreendedor no estudo'], 1,
    'Sem sistema, zona e datum a coordenada não é reproduzível, e a conferência espacial deixa de ser auditável.',
    { sec: 'pop-section-103', quote: 'Coordenadas devem indicar sistema, zona, datum e unidade.' }],
  ['m13', 'Depois de gerar o PDF de uma Informação Técnica, a equipe encontra uma tabela cortada. Qual controle deveria ter detectado o problema?',
    ['Revisão ortográfica do texto extraído', 'Inspeção visual de todas as páginas renderizadas', 'Conferência amostral da primeira e da última página'], 1,
    'Cortes, sobreposições, quebras indevidas de tabela e imagens deslocadas só aparecem no arquivo renderizado.',
    { sec: 'pop-section-107', quote: 'o arquivo deve ser renderizado para PDF ou imagens e todas as páginas devem ser inspecionadas' }],
  ['m13', 'Nas tabelas de checklist, o status "Apresenta" equivale a "suficiente"?',
    ['Sim, apresentar o documento encerra a verificação', 'Não; apresentar não significa automaticamente suficiente', 'Sim, quando o documento tiver ART'], 1,
    'Por isso a tabela mantém colunas distintas para exigibilidade, status, gravidade, achado, consequência técnica e encaminhamento.',
    { sec: 'pop-section-105', quote: 'não significa automaticamente' }],

  // ---------- M14 Anexos, referencias e caso integrador ----------
  ['m14', 'O que os campos "A conferir" e "A definir" indicam no modelo de checklist consolidado?',
    ['Itens que já foram auditados e ainda aguardam assinatura', 'Modelo em branco, que não representa resultado de auditoria', 'Itens dispensados para aquele empreendimento'], 1,
    'O modelo é ponto de partida a ser adaptado ao processo concreto, e seus campos vazios não podem ser lidos como conclusão.',
    { sec: 'pop-section-110', quote: 'identificam modelo em branco e não representam resultado de auditoria' }],
  ['m14', 'Itens críticos podem ser convertidos em condicionantes?',
    ['Sim, para permitir o deferimento com acompanhamento posterior', 'Não, se impedirem decisão segura', 'Sim, desde que com prazo curto de cumprimento'], 1,
    'Condicionante organiza o que é controlável ao longo da fase; ela não resolve o que impede decidir com segurança agora.',
    { sec: 'pop-section-110', quote: 'Itens críticos não devem ser convertidos em condicionantes se impedirem decisão segura.' }],
  ['m14', 'Restrição material do Plano de Manejo que torna a localização incompatível pode virar condicionante?',
    ['Sim; a incompatibilidade pode ser convertida em condicionante com prazo para adequação após a emissão da licença', 'Não; os modelos do anexo só servem quando o empreendimento é compatível com a norma territorial', 'Sim; desde que o empreendedor concorde com a obrigação e apresente cronograma de ajuste do uso territorial'], 1,
    'Incompatibilidade locacional é questão de mérito da localização, não obrigação a ser acompanhada por condicionante.',
    { sec: 'pop-section-123', quote: 'restrição material do ato de criação ou do Plano de Manejo que torne a localização, a estrutura ou a operação incompatível não deve ser transformada em condicionante' }],
  ['m14', 'Uma sigla hipervinculada abriu uma norma externa em vez da definição interna. Qual correção restaura a função prevista no Anexo E?',
    ['Manter a norma externa e acrescentar uma nova aba', 'Redirecionar a sigla para sua definição no anexo de siglas e abreviações', 'Marcar a sigla como termo pendente de revisão'], 1,
    'O anexo consolida as siglas usadas no procedimento e serve de referência única para a leitura.',
    { sec: 'pop-section-124', quote: 'As ocorrências hipervinculadas no texto direcionam para a respectiva definição neste anexo.' }],

  // ---------- M15 Unidades de conservacao, APAs e Planos de Manejo ----------
  ['m15', 'Quais unidades o art. 25 do SNUC exclui da exigência de zona de amortecimento?',
    ['Parques Nacionais e Estações Ecológicas', 'APA e RPPN', 'Reservas Extrativistas'], 1,
    'Daí a proibição de criar zona de amortecimento presumida para APA ou usar raios fixos como se fossem ZA.',
    { sec: 'pop-section-135', quote: 'O art. 25 do SNUC prevê zona de amortecimento para as UCs, exceto APA e RPPN.' }],
  ['m15', 'A existência de propriedade privada dentro de uma APA afasta as restrições do Poder Público?',
    ['Sim, em terras privadas prevalece a decisão do proprietário', 'Não; a APA pode abranger terras públicas e privadas, e as restrições permanecem', 'Sim, quando não houver Plano de Manejo'], 1,
    'A APA integra o grupo de Uso Sustentável, e o licenciamento deve respeitar o ato de criação, o Plano de Manejo e o zoneamento.',
    { sec: 'pop-section-138', quote: 'A APA integra o grupo de Uso Sustentável e pode abranger terras públicas e privadas.' }],
  ['m15', 'A revisão posterior de um Plano de Manejo reabre automaticamente a viabilidade locacional em RLO?',
    ['Sim, o plano novo se aplica integralmente ao empreendimento existente', 'Não por si só, sem fato novo, mas pode estabelecer regras materiais para a fase atual', 'Não, em nenhuma hipótese'], 1,
    'A distinção é entre reabrir a decisão locacional já tomada e observar regras materiais de operação, manutenção ou novas intervenções.',
    { sec: 'pop-section-139', quote: 'A publicação ou revisão posterior de Plano de Manejo não autoriza, por si só, reabrir automaticamente a viabilidade locacional de RLO sem fato novo' }],
  ['m15', 'Por qual ato foi aprovado o Plano de Manejo 2026 da APA Estadual da Escarpa Devoniana?',
    ['Decreto Estadual nº 9.541/2025', 'Portaria IAT nº 416/2026', 'Resolução CONAMA nº 508/2025'], 1,
    'O caso é citado no POP porque o Plano veda hidrelétricas que resultem em área de alagamento, ressalvado licenciamento válido anterior.',
    { sec: 'pop-section-140', quote: 'Plano de Manejo 2026 aprovado pela Portaria IAT nº 416/2026' }],

  // ---------- M16 Licenciamento federal delegado: ACT e RTAA ----------
  ['m16', 'Até quando o Relatório Técnico Anual de Atividades deve ser encaminhado ao Ibama?',
    ['Até 31 de janeiro de cada ano', 'Até 31 de março de cada ano', 'Até 30 de junho de cada ano'], 1,
    'Essa é a obrigação jurídica permanente enquanto aplicável o ACT; a forma operacional de envio é que precisa ser confirmada a cada exercício.',
    { sec: 'pop-section-147', quote: 'encaminhamento do Relatório Técnico Anual de Atividades ao Ibama até 31 de março de cada ano' }],
  ['m16', 'Em processo federal delegado, de quem é a responsabilidade pela compensação ambiental?',
    ['Do IAT, por executar o licenciamento', 'Do Ibama, salvo previsão expressa em sentido contrário', 'Da Câmara Técnica estadual, em qualquer caso'], 1,
    'Por isso a compensação não deve ser direcionada automaticamente ao fluxo estadual sem a leitura do ACT específico.',
    { sec: 'pop-section-152', quote: 'permanecem, salvo previsão expressa em sentido contrário, sob responsabilidade do Ibama' }],
  ['m16', 'Se um elemento necessário da ficha de controle do processo delegado não puder ser confirmado, o técnico deve:',
    ['Adotar a informação mais provável e seguir', 'Registrar como Pendente de validação', 'Suspender o processo até a resposta do Ibama'], 1,
    'A ficha registra empreendimento, processos, número e vigência do ACT, objeto, fases, aditivos e cláusulas que afetem a análise.',
    { sec: 'pop-section-145', quote: 'Se algum desses elementos for necessário à decisão e não puder ser confirmado, registrar Pendente de validação.' }],
  ['m16', 'A existência do formulário eletrônico do RTAA dispensa o relatório textual complementar?',
    ['Sim, o formulário eletrônico substituiu integralmente o relatório textual desde a sua adoção', 'Não se pode concluir isso por si só; a necessidade se verifica no ACT e nas orientações do exercício', 'Sim, desde que os documentos técnicos sigam no mesmo peticionamento'], 1,
    'Em 2026 houve caso de formulário, relatório textual, licença e documentos técnicos peticionados conjuntamente no processo SEI/IBAMA.',
    { sec: 'pop-section-150', quote: 'A existência de formulário eletrônico não permite concluir, por si só, que relatório textual complementar deixou de ser utilizado.' }],
];
