// Montagem do banco de questoes.
//
// Saiu de courseData.js em 01/08/2026, pelo mesmo motivo dos cenarios: a linha
// 1 de courseData importava questionsExtra.js, e como main.jsx importa tracks e
// trackGroups de courseData, os 35 kB de questoes entravam no pacote de quem
// nunca abriu uma avaliacao.
//
// Este modulo continua sendo a FONTE de autoria: os testes e o portao
// check-questoes leem daqui. A aplicacao le src/data/question-bank.json, que
// tools/build-question-data.mjs deriva deste arquivo e confere com --check.
import { QUESTOES_EXTRA } from './questionsExtra.js';
import { QUESTOES_COBERTURA } from './questionsCoverage.js';

const QUESTION_ORDINALS = new Map();
function buildQuestion(q, i) {
  const track = q[0];
  const ordinal = QUESTION_ORDINALS.get(track) || 0;
  QUESTION_ORDINALS.set(track, ordinal + 1);
  const options = [...q[2]];
  const target = ordinal % options.length;
  const originalAnswer = q[3];
  [options[target], options[originalAnswer]] = [options[originalAnswer], options[target]];
  return {
    id: `q${String(i + 1).padStart(3, '0')}`,
    track,
    question: q[1],
    options,
    answer: target,
    explanation: q[4],
    ...(q[5] ? { source: q[5] } : {}),
  };
}

export const questionBank = [
  ['m00','Uma exigência documental ao empreendedor precisa ter fundamento aplicável?',['Não; a prática interna da equipe basta para criar a exigência','Sim; deve haver fundamento aplicável, não apenas o POP','Somente quando o documento também estiver previsto em processo semelhante'],1,'O POP organiza o método, mas não cria exigência autônoma.',{"sec":"pop-section-003","quote":"Este procedimento não cria exigência documental autônoma."}],
  ['m01','Qual registro é indispensável em processo sujeito a transição?',['Somente a data do protocolo e a norma vigente na data da decisão','Datas, estágio, regime aplicado e justificativa','Apenas o estágio atual e a identificação da regra mais recente'],1,'A motivação precisa separar e documentar as transições aplicáveis.',{"sec":"pop-section-006","quote":"devem ser registrados a data do protocolo, a data de entrada em vigor considerada conforme o art. 67, o estágio processual existente nessa data, o regime jurídico aplicado e a justificativa"}],
  ['m01','Quando há conflito aparente de modalidades ou competência, o técnico deve:',['Escolher a modalidade considerada mais cautelosa e registrar sua interpretação no parecer','Adotar a competência indicada no requerimento e seguir a análise até haver contestação','Registrar pendência e buscar validação jurídica ou institucional'],2,'Dúvida normativa relevante exige validação, não criação de regra pelo analista.',{"sec":"pop-section-008","quote":"registrar a pendência como Pendente de validação"}],
  ['m02','A leitura inicial recomendada é:',['Cronológica e temática','Apenas pelo documento mais recente','Começando pela conclusão anterior'],0,'O objeto e o histórico vêm antes do juízo de suficiência.',{"sec":"pop-section-017","quote":"A leitura do processo deve ser feita de forma cronológica e temática."}],
  ['m02','Documento de outro empreendimento tende a ser classificado como:',['Vencido, desde que esteja formalmente assinado pelo responsável técnico','Inconsistente e geralmente crítico','Insuficiente, pela simples ausência de atualização'],1,'A incompatibilidade de objeto impede o uso seguro do documento.',{"sec":"pop-section-019","quote":"Documento de outro empreendimento ou outro corpo hídrico deve ser classificado como inconsistente, e a inconsistência impede a decisão até ser sanada."}],
  ['m03','No enquadramento estadual, potência e área de alagamento são aplicadas:',['Pelo critério menos restritivo','Pelo critério mais restritivo','Somente após a decisão'],1,'O POP orienta a prevalência do critério mais restritivo.',{"sec":"pop-section-020","quote":"primeiro potência e área de alagamento, com prevalência do critério mais restritivo"}],
  ['m03','Enquadramento da modalidade e suficiência documental devem ser verificados separadamente?',['Não; modalidade adequada comprova suficiência para deferir','Sim; modalidade adequada não prova suficiência documental','Somente quando o pedido envolver EIA/RIMA'],1,'Enquadramento e suficiência documental são análises distintas.',{"sec":"pop-section-020","quote":"A modalidade pode estar adequada, mas a documentação ainda ser insuficiente para deferimento."}],
  ['m04','A DLAM preserva a necessidade de outorga e autorizações específicas quando forem aplicáveis?',['Não; a dispensa ambiental elimina os demais atos','Sim; a DLAM preserva os demais atos exigíveis','Somente para MCH'],1,'Dispensa ambiental não elimina outros atos exigíveis.',{"sec":"pop-section-029","quote":"Conferir se a dispensa estadual não afasta obrigações de outorga, ANEEL, município, dominialidade, APP, fauna, flora"}],
  ['m05','A LP tem como foco principal:',['Autorizar o início da operação','Viabilidade, localização e concepção','Renovar as condicionantes vigentes'],1,'A instalação e a operação possuem fases próprias.',{"sec":"pop-section-033","quote":"A LP avalia localização e concepção"}],
  ['m05','Na LO, uma verificação central é:',['Pagamento da taxa e regularidade cadastral do titular','Implantação conforme autorizado e desempenho ambiental','Potência instalada e data prevista de início da operação'],1,'A LO confronta obra, programas e condições para operação.',{"sec":"pop-section-038","quote":"A LO deve verificar se o empreendimento foi implantado conforme licença e projeto aprovado"}],
  ['m06','Mudança de titularidade sem formalização adequada é:',['Irrelevante para a análise','Pendência potencialmente crítica','Resolvida por troca de e-mail'],1,'Titular, outorga, ANEEL e assunção de obrigações precisam ser compatíveis.',{"sec":"pop-section-019","quote":"Mudança de titularidade sem ato administrativo formal, anuência, assunção de condicionantes e compatibilidade com outorga e ANEEL deve ser tratada como pendência crítica."}],
  ['m06','Repotenciação deve ser analisada:',['Apenas pelo nome dado pelo requerente','Pelos efeitos técnicos e ambientais concretos','Sempre como renovação'],1,'A materialidade da alteração define o tratamento.',{"sec":"pop-section-050","quote":"Alterações em empreendimentos hidrelétricos devem ser avaliadas conforme natureza, escala, fase, impactos adicionais e relação com a licença vigente."}],
  ['m07','O licenciamento ambiental deve preservar a competência do órgão fiscalizador da barragem?',['Não; o licenciamento assume a fiscalização estrutural','Sim; integrar evidências não substitui o órgão fiscalizador','Somente na Zona de Autossalvamento'],1,'A análise integra evidências, respeitando limites de competência.',{"sec":"pop-section-053","quote":"sem substituir a competência do órgão fiscalizador"}],
  ['m08','Plano de trabalho e relatório de execução cumprem funções distintas?',['Não; qualquer plano com ART comprova a execução','Sim; plano projeta ações e relatório comprova execução e resultados','Somente quando o programa ambiental tiver condicionante própria'],1,'O plano descreve futuro; o relatório comprova execução e resultados.',{"sec":"pop-section-074","quote":"Plano de trabalho, cronograma futuro ou descrição de intenção não substituem relatório de execução."}],
  ['m08','Um documento assinado ainda precisa ter conteúdo e compatibilidade avaliados?',['Não; assinatura e ART válidas demonstram suficiência material','Sim; formalidade não substitui análise técnica do conteúdo','Somente quando não se tratar de EIA/RIMA'],1,'Formalidade não substitui suficiência material.',{"sec":"pop-section-057","quote":"Este capítulo orienta a análise do conteúdo técnico, e não apenas a presença formal do arquivo."}],
  ['m09','As UTHs do PACUERA devem derivar de:',['Da divisão do entorno conforme limites municipais e matrículas dominiais disponíveis','Diagnóstico integrado de fragilidades e potencialidades','Da repetição das zonas de uso adotadas no Plano Diretor municipal incidente'],1,'As unidades sustentam tecnicamente o zoneamento.',{"sec":"pop-section-070","quote":"Unidades Territoriais Homogêneas resultantes da síntese das fragilidades e potencialidades naturais e antrópicas"}],
  ['m09','Como a conclusão técnica deve classificar o PACUERA?',['Somente como aprovado ou reprovado, conforme o parecer da equipe','Como Apresenta, Insuficiente, Inconsistente, Pendente de validação ou Não se aplica','Apenas pela quantidade de itens do Termo de Referência efetivamente atendidos'],1,'A conclusão separa conformidade ao TR, suficiência do diagnóstico, consistência do zoneamento, cartografia, participação social e possibilidade de implementação. O encaminhamento decorre da consequência sobre a gestão territorial e a decisão segura.',{"sec":"pop-section-072","quote":"O PACUERA pode ser classificado como Apresenta, Insuficiente, Inconsistente, Pendente de validação ou Não se aplica"}],
  ['m10','Um empreendimento complexo exige geometrias que permitam delimitar suas áreas e estruturas?',['Não; um ponto isolado basta quando há escala','Sim; é preciso localizar, delimitar e quantificar impactos','Somente quando o reservatório ultrapassar o município de origem'],1,'Poligonais e arquivos geoespaciais são necessários quando a análise depende da área.',{"sec":"pop-section-076","quote":"O analista deve verificar se mapas e arquivos digitais permitem localizar, delimitar e quantificar impactos."}],
  ['m11','A análise do IAT deve respeitar a manifestação de competência do IPHAN?',['Não; o analista ambiental pode substituí-la','Sim; é preciso respeitar a competência externa','Somente no licenciamento simplificado'],1,'A interface deve ser verificada sem invadir competência externa.',{"sec":"pop-section-082","quote":"A atuação do IAT deve respeitar competências setoriais"}],
  ['m11','A vistoria deve registrar:',['Somente registros fotográficos georreferenciados e a lista de participantes','Achados, localização, evidências e relação com o processo','As conclusões finais de viabilidade, ainda que não estejam apoiadas em fatos observados'],1,'Rastreabilidade de campo é parte do produto técnico.',{"sec":"pop-section-087","quote":"O relatório de vistoria deve registrar fatos observados"}],
  ['m12','Uma boa pendência indica:',['A identificação do documento faltante, acompanhada apenas de prazo padronizado para entrega','Lacuna, fundamento, consequência e providência','O pedido genérico de complementação, desde que repita a lista integral do Termo de Referência'],1,'A redação deve permitir compreender e sanear a lacuna.',{"sec":"pop-section-092","quote":"Cada item deve manter nexo com a fase, o impacto e a decisão."}],
  ['m12','Condicionante de qualidade deve ser:',['Ampla o bastante para cobrir situação não prevista','Clara, verificável, proporcional e ligada ao impacto','Copiada do modelo do anexo, sem ajuste ao caso'],1,'Objeto, entrega, prazo e critério de verificação precisam ser definidos.',{"sec":"pop-section-094","quote":"Devem ser claras, mensuráveis, verificáveis, proporcionais e acompanhadas de prazo e forma de comprovação."}],
  ['m13','A revisão final deve conferir coerência entre:',['Título, numeração, assinatura e data de emissão','Análise, conclusão, pendências e condicionantes','Anexos, referências e a ordem dos documentos'],1,'Inconsistências internas comprometem a decisão e a rastreabilidade.',{"sec":"pop-section-108","quote":"toda manifestação deve passar por auditoria interna de coerência técnica, normativa, documental, linguística e visual"}],
  ['m14','Os modelos dos anexos devem ser usados:',['Sem adaptação','Como base adaptável ao caso concreto','Somente pelos coordenadores da unidade'],1,'Modelos apoiam padronização, mas não substituem análise específica.',{"sec":"pop-section-123","quote":"Os modelos abaixo são exemplos e devem ser adaptados ao caso concreto."}],
  ["m00","Segundo o POP, para quem o procedimento foi elaborado?",["Exclusivamente para servidores recém-ingressos, como material de treinamento inicial","Para orientar recém-ingressos e uniformizar a atuação de equipes experientes","Apenas para coordenadores e revisores responsáveis pela aprovação final"],1,"O POP cumpre dupla função: orienta quem está chegando e padroniza a prática de quem já tem experiência, sem excluir nenhum perfil do público-alvo.",{"sec":"pop-section-003","quote":"orientar profissionais recém-ingressos e também para uniformizar a atuação de equipes experientes"}],
  ["m00","Quanto aos limites do POP, é correto afirmar que ele:",["Substitui a outorga de direito de uso de recursos hídricos sempre que o processo estiver completo","Dispensa a manifestação do IPHAN em empreendimentos de pequeno porte","Mantém exigíveis os demais atos e manifestações cabíveis"],2,"O POP organiza a atuação técnica interna, mas atos e manifestações de competência jurídica ou de outros órgãos permanecem exigíveis por suas próprias vias.",{"sec":"pop-section-003","quote":"o POP não substitui manifestação jurídica, outorga de recursos hídricos, ato setorial da ANEEL, manifestação do IPHAN"}],
  ["m00","Quando não houver elemento suficiente para concluir a análise, o técnico deve:",["Concluir mesmo assim, presumindo a regularidade do empreendimento","Registrar a limitação de forma explícita e proporcional","Devolver o processo sem qualquer registro, aguardando nova documentação"],1,"A insuficiência de elementos não autoriza conclusão presumida nem silêncio: o POP exige que a limitação seja documentada de modo explícito e proporcional.",{"sec":"pop-section-003","quote":"Quando não houver elemento suficiente para concluir, o técnico deve registrar a limitação de forma explícita e proporcional."}],
  ["m01","Ao verificar outorgas, atos setoriais e manifestações externas em um processo de hidrelétrica, a unidade de licenciamento do IAT deve:",["Substituir a decisão do órgão legalmente competente sempre que houver urgência no processo","Verificar a existência e a compatibilidade desses atos, sem substituir a decisão do órgão competente","Emitir os atos setoriais faltantes em nome do empreendedor"],1,"O POP delimita o papel da unidade de licenciamento: conferir existência e compatibilidade dos atos externos, respeitando a competência decisória de cada órgão, que permanece intransferível.",{"sec":"pop-section-004","quote":"verificar a existência e a compatibilidade de outorgas, atos setoriais e manifestações externas, mas não pode substituir a decisão técnica ou administrativa do órgão competente"}],
  ["m01","Na ordem operacional de consulta às fontes normativas, qual é a posição dos Termos de Referência, condicionantes e orientações internas?",["Prevalecem sobre a lei e sobre o regulamento sempre que forem editados mais recentemente","Têm hierarquia equivalente à de um decreto estadual em vigor","Detalham a instrução técnica do caso concreto, subordinados à lei e ao regulamento"],2,"A ordem de consulta não equipara atos de natureza distinta: instrumentos de detalhamento técnico orientam a instrução do caso, mas ficam subordinados à lei e ao regulamento.",{"sec":"pop-section-005","quote":"Termos de Referência, condicionantes e orientações internas não prevalecem sobre lei ou regulamento, mas detalham a instrução técnica do caso concreto"}],
  ["m01","Com a vigência da Lei Federal nº 15.190/2025, como a análise deve tratar a matriz estadual de enquadramento da IN IAT nº 09/2025?",["Presumir sua revogação automática pelo regime federal","Mantê-la como referência operacional, compatibilizada com as disposições federais vigentes","Aplicá-la isoladamente, ignorando procedimentos federais supervenientes"],1,"A lei federal traz normas gerais e admite licenças específicas dos entes federativos; por isso a matriz estadual continua valendo como referência, desde que compatibilizada com o regime federal.",{"sec":"pop-section-007","quote":"a matriz estadual da IN IAT nº 09/2025 permanece referência operacional para o enquadramento no Paraná, mas deve ser compatibilizada com as disposições federais vigentes"}],
  ["m02","Segundo o fluxo geral de análise de processo hidrelétrico, a conclusão do analista deve resultar de quê?",["Da compatibilização documental e técnica do processo","Da conclusão adotada no parecer anterior do mesmo empreendimento","Do documento mais recente juntado ao protocolo"],0,"O fluxo geral existe justamente para impedir que a análise comece pela conclusão: o juízo final só se sustenta após confrontar os documentos e os elementos técnicos do processo.",{"sec":"pop-section-015","quote":"O objetivo é impedir que a análise comece pela conclusão. A conclusão deve resultar da compatibilização documental e técnica."}],
  ["m02","Na triagem, em qual situação a saída correta é a diligência técnica, e não a diligência documental?",["Quando faltam documentos exigíveis ou há documento vencido ou ilegível","Quando há estudo apresentado, mas com lacuna técnica que impede decisão segura","Quando o tema depende de outorga, IPHAN, ANEEL ou outro interveniente"],1,"A diligência documental trata de ausência ou invalidade de documentos; a diligência técnica se aplica quando o estudo existe, porém contém lacuna que impede decisão segura, gerando pedido de complementação fundamentado.",{"sec":"pop-section-016","quote":"Há estudo, mas com lacuna técnica que impede decisão segura."}],
  ["m02","Quando a análise depende da delimitação espacial do empreendimento, o que determina o alerta de triagem sobre a cartografia apresentada?",["Aceitar ponto isolado em mapa como delimitação suficiente do empreendimento","Substituir a cartografia pelo plano de trabalho dos programas ambientais","Exigir poligonais e arquivos geoespaciais do empreendimento"],2,"Um ponto isolado em mapa não delimita empreendimento hidrelétrico complexo; por isso a triagem deve exigir poligonais e arquivos geoespaciais sempre que a análise depender de delimitação espacial.",{"sec":"pop-section-019","quote":"Exigir poligonais e arquivos geoespaciais quando a análise depender de delimitação espacial."}],
  ["m03","Sobre a manifestação emitida na Consulta Prévia, é correto afirmar que ela:",["Assegura prioridade ao requerente e equivale à aprovação da viabilidade ambiental","Tem validade de 24 meses, não é prorrogável e não equivale à aprovação de viabilidade ambiental","Vale por prazo indeterminado enquanto o arranjo do projeto não for alterado"],1,"A Consulta Prévia orienta o requerente antes da formalização da licença, mas não gera direito de prioridade, domínio nem juízo definitivo de viabilidade; sua validade é de 24 meses, sem prorrogação.",{"sec":"pop-section-024","quote":"A manifestação tem validade de 24 meses, não é prorrogável, não assegura prioridade, não confere domínio e não equivale à aprovação de viabilidade ambiental."}],
  ["m03","Conforme o art. 36 da IN IAT nº 09/2025, a entrada mínima esperada para a Consulta Prévia compreende:",["EIA/RIMA completo acompanhado da outorga de uso da água","Apenas o requerimento assinado, sem qualquer material cartográfico","Mapa da delimitação da ADA, mapa digital do arranjo em KML ou KMZ e Memorial Descritivo"],2,"A entrada mínima é composta por peças de localização e descrição do arranjo, sem prejuízo de complementações; estudos ambientais completos pertencem a fases posteriores do licenciamento.",{"sec":"pop-section-025","quote":"a entrada mínima compreende mapa da delimitação da ADA, mapa digital do arranjo em formato KML ou KMZ e Memorial Descritivo"}],
  ["m03","Qual é a relação entre a classificação ambiental adotada pelo IAT e o regime setorial da ANEEL?",["O registro na ANEEL substitui o enquadramento ambiental estadual","Uma classificação não substitui a outra, pois cada uma serve a finalidade própria","O enquadramento ambiental do IAT dispensa os atos do setor elétrico"],1,"A classificação do IAT serve ao enquadramento do licenciamento no Paraná, enquanto o regime da ANEEL trata do aproveitamento do potencial hidráulico e dos atos do setor elétrico; os dois regimes convivem sem se substituir.",{"sec":"pop-section-023","quote":"Uma classificação não substitui a outra."}],
  ["m04","Segundo o POP, quais critérios uma CGH deve atender para ser elegível à LAC?",["Potência de até 1 MW, alagamento inferior a 5 ha, IDA menor que 3 e ausência de necessidade de autorização de supressão","Potência de até 5 MW, alagamento inferior a 10 ha e IDA maior ou igual a 3","Apenas potência de até 1 MW, independentemente de alagamento, de IDA ou de supressão de vegetação nativa","IDA maior ou igual a 3, desde que haja autorização de supressão já emitida"],0,"Para CGH, a LAC exige a combinação dos quatro critérios: potência, alagamento, IDA e ausência de supressão; qualquer divergência afasta a conclusão automática pela adesão.",{"sec":"pop-section-030","quote":"Para CGH, a IN prevê LAC para potência de até 1 MW, alagamento inferior a 5 ha, IDA menor que 3"}],
  ["m04","Na análise de um pedido de DLAM, quando não for possível confirmar a hipótese normativa de dispensa, o que o POP determina?",["Encaminhar como DLAM mesmo assim, desde que a potência declarada seja baixa","Confirmar a hipótese normativa, sem decidir só pela potência declarada","Converter automaticamente o processo em licenciamento trifásico","Aceitar a dispensa mediante simples declaração do empreendedor"],1,"A potência declarada, isoladamente, não sustenta a dispensa: a hipótese normativa precisa ser confirmada, inclusive quanto à inexistência de supressão compatível com o arranjo e a cartografia.",{"sec":"pop-section-029","quote":"Quando não for possível confirmar a hipótese de dispensa, o processo não deve ser encaminhado como DLAM apenas com base na potência declarada."}],
  ["m04","Quanto à natureza dos institutos, como o POP classifica DLAM, LAC e LAS?",["As três são modalidades monofásicas de licenciamento","A DLAM é ato de dispensa; LAC e LAS são modalidades monofásicas","A DLAM é modalidade monofásica; LAC e LAS são atos de dispensa"],1,"O POP distingue a natureza jurídica dos institutos: a DLAM não é licença, e sim ato de dispensa, enquanto LAC e LAS são modalidades de licenciamento em fase única.",{"sec":"pop-section-028","quote":"A DLAM deve ser tratada como ato de dispensa, enquanto LAC e LAS constituem modalidades monofásicas."}],
  ["m05","Qual é o gatilho tipológico numérico que o POP explicita para exigir EIA e RIMA de uma PCH na fase de LP?",["Potência acima de 10 MW ou alagamento superior a 100 ha","Qualquer outorga de uso da água vigente, sem considerar porte ou impacto","Alagamento superior a 1.000 ha, independentemente da potência","Solicitação voluntária do estudo pelo empreendedor"],0,"Esses são os dois gatilhos numéricos expressos para PCH. Eles não esgotam as hipóteses: a exigência também alcança UHE e empreendimento inicialmente simplificado que o IAT considere potencialmente impactante; nos demais casos, devem ser consultados o enquadramento e o TR vigente.",{"sec":"pop-section-034","quote":"A exigência de EIA e RIMA aplica-se às UHEs, às PCHs com potência acima de 10 MW ou alagamento superior a 100 ha e aos empreendimentos inicialmente simplificados que o IAT considere potencialmente impactantes"}],
  ["m05","Na análise da Licença de Instalação, o projeto apresentado deve ter nível de detalhamento suficiente para:",["Demonstrar alternativas locacionais e tecnológicas do empreendimento","Controlar impactos de obra e executar os programas ambientais","Comprovar o desempenho ambiental da operação já iniciada","Substituir as condicionantes estabelecidas na LP"],1,"A LI é a fase de controle da implantação: o projeto precisa detalhar como os impactos de obra serão controlados e os programas executados. Alternativas locacionais pertencem à LP e desempenho da operação, à LO.",{"sec":"pop-section-036","quote":"A LI depende de projeto com nível de detalhamento suficiente para controlar impactos de obra, executar programas ambientais"}],
  ["m05","Nos processos sujeitos a EIA, qual regra de participação pública o POP estabelece antes da decisão sobre a LP?",["EIA e RIMA disponíveis ao público por, no mínimo, 45 dias antes da audiência pública","Audiência pública realizada somente após a emissão da LI","Disponibilização dos estudos por 15 dias, contados após a decisão final","A audiência pública do PACUERA substitui a audiência da LP"],0,"Deve haver pelo menos uma audiência pública antes da decisão final sobre a LP, com EIA e RIMA acessíveis ao público por no mínimo 45 dias antes dela. Esse rito não se confunde com a participação social do PACUERA.",{"sec":"pop-section-040","quote":"O EIA e o RIMA devem permanecer disponíveis ao público por, no mínimo, 45 dias antes da audiência."}],
  ["m06","Segundo o POP, qual é o alcance correto da Autorização Ambiental (AA) na IN IAT nº 09/2025?",["A AA pode substituir a licença principal quando o empreendedor demonstrar urgência na operação.","A AA tem aplicação expressa para enchimento de reservatório e testes de comissionamento, mas não substitui a licença principal nem a outorga.","A AA dispensa a manifestação de intervenientes e a Autorização Florestal durante a fase de comissionamento."],1,"A AA é restrita às hipóteses previstas, como enchimento de reservatório e testes de comissionamento, e não substitui os demais títulos e autorizações exigíveis.",{"sec":"pop-section-041","quote":"A AA não substitui licença principal, Autorização Florestal, outorga, manifestação de interveniente ou licenciamento de ampliação quando houver alteração substancial."}],
  ["m06","Na análise de renovação e operação existente (RLO, RLAS, LASR, LOR), qual deve ser o foco do técnico?",["A regularidade atual, a situação fática e a continuidade da operação, sem rediscutir integralmente a viabilidade locacional já apreciada.","Rediscutir integralmente a viabilidade locacional em toda renovação, como se fosse um novo licenciamento.","Conferir apenas a data de validade da licença anterior, sem examinar a situação fática do empreendimento."],0,"A renovação foca a regularidade atual e a continuidade da operação; a viabilidade locacional só é reaberta diante de fato novo, alteração ou irregularidade.",{"sec":"pop-section-043","quote":"a análise deve focar a regularidade atual, a situação fática e a continuidade da operação, sem rediscutir integralmente a viabilidade locacional já apreciada"}],
  ["m06","Em um processo de regularização de empreendimento hidrelétrico, o que o POP exige além da conferência documental?",["Basta a juntada dos documentos faltantes para a emissão da licença corretiva.","Toda situação irregular deve ser encaminhada diretamente a novo licenciamento, sem análise de regularização.","Verificar os requisitos e limites do art. 32 da IN IAT nº 09/2025, os passivos e se a situação é tecnicamente regularizável."],2,"A regularização exige avaliar requisitos normativos, passivos, embargos e a possibilidade técnica de manutenção do arranjo, e não apenas juntar documentos.",{"sec":"pop-section-046","quote":"A regularização não se limita à juntada de documentos. Devem ser verificados os requisitos e limites do art. 32 da IN IAT nº 09/2025"}],
  ["m07","Como o POP orienta tratar acessos, canteiros, bota-fora, jazidas e demais áreas de apoio de uma hidrelétrica?",["Devem sempre integrar automaticamente a licença do empreendimento principal","Podem integrar o escopo da licença hidrelétrica ou exigir processo próprio, com decisão justificada","Devem sempre ser licenciados em processo separado, independentemente do vínculo funcional","Ficam dispensados de análise quando estiverem fora do reservatório"],1,"O tratamento depende da relação funcional, localização e potencial de impacto, e a decisão deve registrar o vínculo funcional e a justificativa para análise conjunta ou separada.",{"sec":"pop-section-051","quote":"podem integrar o escopo da licença hidrelétrica ou exigir processo próprio"}],
  ["m07","Na verificação da interface com a segurança de barragens, o que determina a incidência da PNSB sobre o barramento?",["A classificação do empreendimento como PCH ou UHE, de forma automática","A existência de licença de operação vigente","As características e os critérios legais da própria estrutura","A localização do empreendimento dentro do Paraná"],2,"O enquadramento na Política Nacional de Segurança de Barragens é da estrutura, verificado caso a caso, e não decorre apenas da tipologia do empreendimento.",{"sec":"pop-section-054","quote":"A incidência da PNSB não decorre apenas da classificação do empreendimento como PCH ou UHE, devendo ser verificada conforme características e critérios legais da estrutura"}],
  ["m07","Ao encaminhar um processo com risco relacionado à segurança de barragens, o que a manifestação do licenciamento deve conter?",["Declaração de estabilidade estrutural do barramento","Atestado de atendimento definitivo das obrigações junto ao órgão fiscalizador","A consequência ambiental identificada e os limites da própria análise"],2,"A manifestação registra o efeito ambiental e delimita o alcance da análise, pois a validação de estabilidade e de obrigações de segurança pertence a outro órgão.",{"sec":"pop-section-056","quote":"deve registrar a consequência ambiental e os limites da análise, sem declarar estabilidade, segurança estrutural"}],
  ["m08","Ao selecionar o Termo de Referência aplicável ao estudo ambiental, como o analista deve tratar os TR1, TR2 e TR3?",["Como equivalentes entre si, bastando adotar sempre o mais recente que tiver sido publicado","Como documentos com diferenças de escopo e profundidade, que não devem ser tratados como versões automaticamente equivalentes","Como complementares entre si, combinando automaticamente o requisito mais exigente de cada um deles no caso"],1,"O POP determina registrar qual TR foi adotado, a fonte, a data de consulta e a justificativa, justamente porque os TR examinados não são intercambiáveis entre si.",{"sec":"pop-section-057","quote":"Os TR1, TR2 e TR3 examinados possuem diferenças de escopo e profundidade e não devem ser tratados como versões automaticamente equivalentes."}],
  ["m08","Em um processo com Memorial Descritivo desatualizado, mas com estudo ambiental antigo já protocolado, qual é a orientação do POP?",["O estudo ambiental já aprovado supre a defasagem do memorial descritivo e dispensa a sua atualização posterior","O memorial atualizado passa a substituir a análise de impactos apresentada no estudo ambiental","Nenhum documento corrige o outro: estudo antigo não corrige memorial desatualizado e memorial não substitui análise de impactos"],2,"O memorial é o documento-base de engenharia e o estudo ambiental analisa impactos; cada um tem função própria e um não sana a deficiência do outro.",{"sec":"pop-section-060","quote":"Estudo ambiental antigo não corrige memorial desatualizado, e memorial não substitui análise de impactos."}],
  ["m08","Segundo o POP, qual é a função do RDPA em relação ao conteúdo do RAS?",["Reproduzir o diagnóstico do RAS em maior nível de detalhe cartográfico","Transformar as propostas básicas do RAS em programas executáveis e verificáveis","Substituir o RAS como instrumento de avaliação ambiental simplificada"],1,"O RDPA não é cópia ampliada do RAS: ele deve converter as propostas em programas cuja execução, resultado e efetividade possam ser acompanhados.",{"sec":"pop-section-063","quote":"O RDPA deve transformar as propostas básicas do RAS em programas executáveis e verificáveis. Não basta reproduzir o diagnóstico ou copiar o texto do RAS."}],
  ["m09","Conforme o TR PACUERA 2026 citado no POP, qual é a regra de protocolo e de revisão do PACUERA?",["Protocolo apenas na renovação da licença de operação, com revisão a cada 5 anos","Protocolo simultâneo ao PBA ou ao RDPA, conforme a licença e o estudo aplicáveis, com revisão obrigatória a cada 10 anos","Protocolo junto à Consulta Prévia, com revisão somente quando houver alteração do reservatório"],1,"O plano acompanha o PBA ou o RDPA no protocolo e tem ciclo de revisão obrigatória decenal, o que ancora a verificação de vigência da versão analisada.",{"sec":"pop-section-068","quote":"o plano deve ser protocolado simultaneamente ao PBA ou ao RDPA, conforme a licença e o estudo aplicáveis, e revisto obrigatoriamente a cada 10 anos"}],
  ["m09","Qual é o alcance da aprovação do PACUERA pelo IAT?",["Substitui a licença ambiental e a outorga de uso da água em toda a área do entorno do reservatório da usina","Autoriza automaticamente qualquer atividade prevista no zoneamento aprovado, sem novo ato do órgão licenciador","Orienta decisões ambientais dentro da competência do IAT, sem substituir licença, outorga, atos da ANEEL ou manifestação do IPHAN"],2,"A aprovação do PACUERA é instrumento de gestão territorial com efeito orientador, e não título habilitante: cada ato de outro órgão ou de outra competência continua exigível.",{"sec":"pop-section-067","quote":"A aprovação pelo IAT orienta decisões ambientais dentro de sua competência, mas não substitui licença, outorga, ato da ANEEL, manifestação do IPHAN"}],
  ["m09","Na análise de relatórios de condicionantes e programas ambientais, qual entendimento está correto segundo o POP?",["O status declarado pelo empreendedor equivale ao status validado pelo IAT sempre que o relatório estiver assinado por responsável técnico","A apresentação de cronograma futuro é suficiente para comprovar a execução da condicionante","Plano de trabalho, cronograma futuro ou descrição de intenção não substituem relatório de execução, e o status declarado não equivale ao validado"],2,"A comprovação exige relatório de execução com metodologia, resultados e evidências; declaração de intenção ou planejamento futuro não demonstra o que foi de fato realizado.",{"sec":"pop-section-074","quote":"O status declarado pelo empreendedor não equivale ao status validado pelo IAT. Plano de trabalho, cronograma futuro ou descrição de intenção não substituem relatório de execução."}],
  ["m10","Segundo o POP, quais elementos o material cartográfico apresentado no licenciamento de hidrelétricas deve conter?",["Apenas a escala e as coordenadas do ponto central da área, porque os demais elementos são considerados opcionais","Título, legenda, escala, orientação, projeção, datum, data, responsável técnico e compatibilidade com arquivos vetoriais","Somente a assinatura do empreendedor e a data de elaboração do mapa"],1,"O POP lista expressamente os elementos mínimos do material cartográfico, exigidos conforme a fase e a complexidade do arranjo, para que o analista consiga localizar, delimitar e quantificar impactos.",{"sec":"pop-section-076","quote":"O material cartográfico deve conter título, legenda, escala, orientação, projeção, datum, data, responsável técnico e compatibilidade com arquivos vetoriais"}],
  ["m10","Um estudo de fauna foi protocolado antes da vigência da Portaria IAT nº 012/2024. Nos termos do art. 52 citado no POP, qual regra se aplica?",["O estudo deve ser integralmente refeito conforme os Anexos I a VIII da nova Portaria","O estudo passa a seguir as IN IAT nº 01/2023 e nº 02/2023, que continuam vigentes","O estudo segue a norma vigente à época do protocolo","O estudo é automaticamente invalidado e o processo deve ser arquivado"],2,"A regra de transição do art. 52 preserva a norma da época do protocolo; além disso, monitoramentos em instalação ou operação mantêm o desenho amostral aprovado, salvo alteração formal.",{"sec":"pop-section-079","quote":"estudos protocolados antes da vigência da Portaria seguem a norma vigente à época do protocolo"}],
  ["m10","De acordo com o POP, como o analista deve tratar a ausência de outorga vigente ou equivalente em um processo de hidrelétrica?",["Pode ser pendência crítica para licença de instalação, operação e renovação, conforme o caso","É irrelevante, porque a outorga só passa a ser exigida na fase de licença prévia do processo","É sanada automaticamente pela apresentação do memorial descritivo"],0,"O POP determina compatibilizar recursos hídricos entre outorga, memorial, estudo ambiental, SGA e operação, e classifica a falta de outorga vigente como possível pendência crítica nas fases de LI, LO e renovação.",{"sec":"pop-section-080","quote":"Ausência de outorga vigente ou equivalente pode ser pendência crítica para licença de instalação, operação e renovação, conforme o caso."}],
  ["m11","Em pedido de renovação de licença, quanto às manifestações de intervenientes (IPHAN, município, unidades de conservação), o POP orienta que:",["Nova manifestação deve ser exigida automaticamente a cada renovação","Nova manifestação não deve ser exigida sem fato novo, alteração, condicionante ou inconsistência relevante","As manifestações anteriores perdem a validade e o processo precisa ser reiniciado inteiramente do zero"],1,"A renovação aproveita as manifestações já emitidas; só se exige nova manifestação quando houver fato novo, alteração, condicionante ou inconsistência relevante.",{"sec":"pop-section-082","quote":"Em renovação, nova manifestação não deve ser exigida sem fato novo, alteração, condicionante ou inconsistência relevante."}],
  ["m11","Ao verificar a participação das autoridades envolvidas, o que o analista deve distinguir?",["Participação de autoridade envolvida, ciência prevista em norma específica, aprovação do art. 46 do SNUC e observância material do Plano de Manejo","Se houve manifestação escrita e tempestiva do órgão gestor, tratando esse documento como suficiente para participação, ciência, aprovação do art. 46 e compatibilidade com o Plano de Manejo","Apenas a competência administrativa do órgão gestor da UC, pois a ciência normativa, a aprovação do art. 46 e a observância material do Plano de Manejo decorreriam automaticamente dessa competência"],0,"Cada hipótese tem gatilho próprio: não caracterizada uma delas, as demais continuam exigíveis. Os arts. 43 e 44 da Lei nº 15.190/2025 consideram UC ou zona de amortecimento na ADA e excluem a APA desse gatilho específico.",{"sec":"pop-section-086","quote":"A ausência de uma dessas hipóteses não deve ser interpretada como dispensa automática das demais."}],
  ["m11","Nos processos sujeitos a EIA, qual é a regra do POP sobre a audiência pública e a disponibilização dos estudos?",["A audiência é facultativa e pode ocorrer depois da emissão da Licença Prévia, sem prejuízo do rito processual","A audiência substitui a análise técnica das contribuições recebidas durante o período de consulta pública","A audiência é obrigatória antes da decisão final sobre a LP, com EIA e RIMA disponíveis por pelo menos 45 dias"],2,"A participação pública precede a decisão sobre a LP, com disponibilização mínima de 45 dias do EIA e do RIMA; as contribuições ainda devem ser analisadas e registradas.",{"sec":"pop-section-142","quote":"A audiência pública é obrigatória nos processos sujeitos a EIA antes da decisão final sobre a LP"}],
  ["m12","Segundo o POP, qual é a divisão de papéis entre o checklist, a Informação Técnica e o Parecer Técnico Conclusivo?",["O checklist controla a instrução, a Informação Técnica interpreta o conjunto e o Parecer Técnico Conclusivo apresenta conclusão motivada","A Informação Técnica deve reproduzir integralmente o checklist para garantir rastreabilidade da análise","O Parecer Técnico Conclusivo controla a instrução documental e dispensa a elaboração de Informação Técnica"],0,"Cada produto tem função própria: o checklist é matriz de controle, a Informação Técnica explica relevância e compatibilidade dos documentos, e o parecer conclui com motivação, dentro da competência do signatário.",{"sec":"pop-section-090","quote":"O checklist controla a instrução; a Informação Técnica interpreta o conjunto; o Parecer Técnico Conclusivo deve observar a competência institucional e apresentar conclusão motivada."}],
  ["m12","Como o POP orienta a comunicação da diligência (minuta de pendências) ao interessado?",["Em etapas sucessivas, à medida que cada documento for sendo analisado pelo técnico responsável pela instrução do processo","Consolidada após análise integrada e comunicada, em regra, de uma única vez, ressalvados fatos novos ou fundamento superveniente registrado","Somente após a emissão da licença, em conjunto com as condicionantes e o respectivo cronograma de cumprimento"],1,"A regra é a exigência única e consolidada, evitando diligências fracionadas; novas exigências só se justificam por fato novo ou fundamento superveniente devidamente registrado.",{"sec":"pop-section-092","quote":"A diligência deve ser consolidada após análise integrada do processo e comunicada, em regra, de uma única vez"}],
  ["m12","Se uma lacuna sanável impede a conclusão segura, mas não indica inviabilidade definitiva, qual é o encaminhamento previsto no Quadro 42 do POP?",["Emitir manifestação não favorável de imediato, sem oportunidade de saneamento","Registrar a lacuna apenas como condicionante para cumprimento depois da licença","Formular diligência ou complementação objetiva, com base normativa e consequência técnica"],2,"Quando a lacuna impede decidir com segurança, o saneamento deve ocorrer antes da licença por diligência ou complementação. Condicionante só cabe quando os documentos essenciais já são suficientes e a pendência remanescente pode ser tratada de forma proporcional.",{"sec":"pop-section-098","quote":"Há lacuna sanável que impede conclusão segura, mas não indica inviabilidade definitiva."}],
  ["m13","Segundo o padrão documental do IAT, enquanto não houver elaboração, revisão e aprovação formalmente identificadas, como o arquivo deve ser tratado?",["Como versão final, apta a declarar validação institucional","Como minuta técnica, sem declarar validação institucional concluída","Como documento oficial, desde que siga o modelo visual do IAT"],1,"A denominação minuta técnica protege a rastreabilidade: só há validação institucional quando elaboração, revisão e aprovação estão formalmente identificadas no documento.",{"sec":"pop-section-099","quote":"o arquivo deve ser denominado minuta técnica e não pode declarar validação institucional concluída"}],
  ["m13","Nas tabelas de checklist e análise técnica, o que fundamenta concluir que um achado impede a decisão?",["A simples ausência formal de um arquivo listado no checklist","O número total de pendências acumuladas no processo","O efeito do achado sobre decisão, viabilidade, modalidade, outorga, APP e demais pontos sensíveis","A avaliação subjetiva do revisor a respeito da qualidade geral do documento apresentado"],2,"O impedimento decorre da consequência técnica do achado, não da mera falta formal de um arquivo; apresentar um documento tampouco significa que ele seja suficiente.",{"sec":"pop-section-105","quote":"O impedimento à decisão deve decorrer do efeito sobre decisão, viabilidade, modalidade, titularidade, outorga, ANEEL, APP, supressão, interveniente ou segurança jurídica"}],
  ["m13","Qual controle visual é obrigatório antes da entrega de um DOCX técnico do IAT?",["Conferir apenas o texto extraído, pois o conteúdo prevalece sobre a forma","Renderizar o arquivo para PDF ou imagens e inspecionar todas as páginas","Imprimir a primeira e a última página para verificação por amostragem"],1,"A inspeção página a página do arquivo renderizado detecta cortes, sobreposições, quebras indevidas de tabelas e imagens deslocadas que o texto extraído não revela.",{"sec":"pop-section-107","quote":"o arquivo deve ser renderizado para PDF ou imagens e todas as páginas devem ser inspecionadas"}],
  ["m14","Segundo o Anexo A do POP, ao preencher o checklist documental consolidado, como o analista deve tratar itens críticos cuja pendência impede uma decisão segura?",["Convertê-los em condicionantes da licença para não atrasar o deferimento","Mantê-los como impedimento à decisão até o saneamento adequado","Marcá-los como não se aplica, com justificativa"],1,"O Anexo A veda transformar item crítico em condicionante quando a pendência compromete a segurança da decisão; a marcação de não se aplica é reservada a itens realmente inaplicáveis.",{"sec":"pop-section-110","quote":"Itens críticos não devem ser convertidos em condicionantes se impedirem decisão segura."}],
  ["m14","Na estrutura do modelo de Informação Técnica do Anexo B, o que a seção de Conclusão deve fazer?",["Repetir o histórico completo do processo para dar contexto à decisão","Listar apenas as condicionantes propostas para a licença","Separar a adequação da modalidade e a suficiência documental para deferimento"],2,"A conclusão da IT distingue dois juízos diferentes: se a modalidade requerida é adequada e se a documentação é suficiente para deferir; histórico e condicionantes têm seções próprias no modelo.",{"sec":"pop-section-119","quote":"Separar adequação da modalidade e suficiência documental para deferimento."}],
  ["m14","De acordo com o Anexo E do POP, qual é a função das ocorrências de siglas hipervinculadas ao longo do texto?",["Direcionar o leitor para a definição da sigla no próprio anexo","Abrir o texto integral da norma externa que instituiu a sigla","Sinalizar siglas em desuso que devem ser evitadas em novos documentos"],0,"O Anexo E consolida as siglas e abreviações do POP, e os hiperlinks no corpo do texto levam à definição correspondente nesse quadro, não a normas externas.",{"sec":"pop-section-124","quote":"As ocorrências hipervinculadas no texto direcionam para a respectiva definição neste anexo."}],
  ["m15","Na triagem, o que deve ser verificado quanto a unidades de conservação?",["Apenas se o empreendimento estiver dentro dos limites de uma unidade","Se há UC, APA ou zona de amortecimento afetada, com base espacial oficial","Somente unidades de conservação de competência federal"],1,"A triagem verifica UC, APA e zona de amortecimento, apoiada nas bases espaciais oficiais.",{"sec":"pop-section-027","quote":"O analista deve trabalhar com o arranjo integral do empreendimento"}],
  ["m15","Em Área de Proteção Ambiental (APA), o que condiciona a análise?",["A APA impede qualquer empreendimento hidrelétrico","O zoneamento do Plano de Manejo e as regras próprias da APA","Nada, por ser unidade de uso sustentável"],1,"APA admite uso, mas o zoneamento do Plano de Manejo condiciona o que é possível em cada trecho.",{"sec":"pop-section-138","quote":"O licenciamento deve respeitar as normas e restrições estabelecidas para uso das propriedades, o ato de criação, o Plano de Manejo e o zoneamento."}],
  ["m15","O Plano de Manejo é alterado depois de licença já emitida. Como proceder?",["Ignorar, pois a licença é ato jurídico perfeito","Analisar a situação superveniente conforme o POP","Cancelar a licença automaticamente"],1,"Alteração superveniente do Plano de Manejo exige análise da nova situação, sem presumir nem cancelamento nem irrelevância.",{"sec":"pop-section-139","quote":"Para empreendimentos existentes, o analista deve construir histórico de licenças"}],
  ["m15","Qual base deve sustentar a análise espacial de UC e APA?",["Imagem de satélite de acesso livre, sem base cartográfica","GeoPR, GeoParaná e bases oficiais, com rastreabilidade","Croqui produzido pelo próprio empreendedor"],1,"A rastreabilidade da análise espacial se apoia nas bases oficiais (GeoPR e GeoParaná).",{"sec":"pop-section-137","quote":"As camadas do GeoPR são instrumentos de apoio e não substituem a leitura do ato legal."}],
  ["m16","Quando o IAT atua no licenciamento ambiental federal delegado?",["Sempre que o empreendimento for de grande porte ou potência","Quando a competência é originária da União e há delegação formal","Quando o órgão federal estiver sem equipe disponível"],1,"É preciso identificar a competência originária da União e o ato de delegação que autoriza a execução pelo IAT.",{"sec":"pop-section-144","quote":"O primeiro passo é identificar o fundamento da competência."}],
  ["m16","Qual documento define o que o IAT pode e deve fazer na competência delegada?",["A licença ambiental","O Acordo de Cooperação Técnica (ACT)","O Termo de Referência do estudo"],1,"O ACT é o instrumento que delimita as obrigações do IAT como delegatário e precisa ser lido e controlado.",{"sec":"pop-section-145","quote":"O ACT delimita a execução delegada."}],
  ["m16","O que é o RTAA no contexto da delegação federal?",["Registro Técnico anual das Atividades Ambientais","Relatório Técnico Anual de Atividades, de envio anual","Roteiro Temático de Análise Ambiental"],1,"O RTAA é o Relatório Técnico Anual de Atividades, com envio anual conforme o canal e o formulário vigentes.",{"sec":"pop-section-147","quote":"Essa é a obrigação jurídica permanente enquanto aplicável o ACT."}],
  ["m16","Como reduzir retrabalho na elaboração do RTAA?",["Concentrar a coleta e a redação no mês do envio","Manter base contínua e preparação interna ao longo do ano","Delegar integralmente ao empreendedor e revisar no fim"],1,"A preparação interna contínua ao longo do ano evita o acúmulo e reduz retrabalho no fechamento anual.",{"sec":"pop-section-149","quote":"O objetivo é evitar reconstrução retrospectiva do processo às vésperas do prazo anual."}],
  ["m12","Segundo o POP, a compensação por impactos não mitigáveis segue qual procedimento?",["Negociação direta com o empreendedor","O procedimento do Decreto Estadual nº 7.150/2024","Livre arbítrio do analista"],1,"A compensação ambiental por impactos negativos não mitigáveis segue o procedimento do Decreto Estadual nº 7.150/2024.",{"sec":"pop-section-155","quote":"O art. 2º do Decreto Estadual nº 7.150/2024 alcança pessoas físicas ou jurídicas responsáveis por empreendimentos"}],
  ["m12","Impacto não mitigável identificado em fase posterior ou em ampliação:",["Não gera compensação nem condicionante, por ser fato superveniente ao estudo","Deve ser tratado conforme o regime aplicável, inclusive em fases posteriores","Só é tratado na renovação da licença de operação seguinte"],1,"O POP trata expressamente processos em fases posteriores, ampliações e impactos supervenientes.",{"sec":"pop-section-157","quote":"O art. 13 estabelece regra específica para empreendimentos ou atividades causadores de impactos negativos não mitigáveis que não tiveram a compensação definida na fase de LI ou LAS"}],
  ...QUESTOES_EXTRA,
  ...QUESTOES_COBERTURA,
].map(buildQuestion);
