// Montagem dos cenarios do Laboratorio.
//
// Saiu de courseData.js em 01/08/2026. La, a linha 1 importava labCases.js, e
// como main.jsx importa tracks, questionBank e trackGroups de courseData, os
// 70 kB de casos entravam no caminho principal de quem so queria abrir uma aula.
// O orcamento de JS estava em 99,6% do teto por causa disso, entre outras
// coisas.
//
// Este modulo continua sendo a FONTE de autoria: os testes e o portao
// check-rubricas leem daqui. A aplicacao, em runtime, le o indice leve e busca
// os corpos sob demanda. tools/build-lab-data.mjs deriva os dois deste arquivo
// e tem modo --check para garantir que nao divergiram.
import {
  NOVOS_CENARIOS,
  RUBRICAS,
  GRUPOS_LAB,
  LAB_TASK_REVISION,
  TAREFAS_LAB,
} from './labCases.js';

const CENARIOS_BASE = [
  {"id":"cp","track":"m03","label":"Consulta Prévia","type":"CGH","title":"CGH com sensibilidade locacional na Consulta Prévia","facts":["Potência de 2,4 MW","Área de alagamento de 18 ha","ADA a cerca de 600 m de unidade de conservação","Requerimento, Memorial preliminar, mapa da ADA e KMZ do arranjo constam da lista de peças, ainda sem conferência de conteúdo"],"evidence":["Requerimento da Consulta Prévia","Memorial preliminar","Mapa da ADA e arranjo em KMZ","Consulta de restrições (UC, cavidades, terras indígenas)"],"steps":["Objeto","Localização","Sensibilidade","Alcance da CP","Encaminhamento"],"questions":[["A simples presença das peças na lista, sem conferir seu conteúdo, basta para considerar objeto e localização suficientemente caracterizados?","nao"],["A proximidade de unidade de conservação deve integrar a manifestação?","sim"],["A manifestação da CP assegura prioridade ou confere domínio ao requerente?","nao"],["A manifestação da CP substitui o licenciamento e o juízo de viabilidade ambiental?","nao"],["A validade de 24 meses da manifestação é prorrogável?","nao"]],"outcome":"Conferir se o Memorial, o mapa da ADA e o arquivo KML ou KMZ caracterizam o arranjo integral e a localização. Se a entrada for suficiente, emitir manifestação orientativa sobre modalidade, estudo provável e restrições de sensibilidade. A manifestação vale 24 meses, não é prorrogável, não assegura prioridade, não confere domínio e não equivale à aprovação de viabilidade ambiental."},
  {"id":"las","track":"m04","label":"LAS","type":"CGH","title":"CGH em LAS com documentação cartográfica incompleta","facts":["Potência de 3 MW; área de alagamento, IDA, supressão e filtros territoriais ainda não foram demonstrados","KMZ apenas com o ponto da barragem","Sem poligonal da ADA nem da casa de força","Anuência municipal apresentada"],"evidence":["Requerimento de LAS","KMZ com ponto único","Memorial descritivo","Anuência municipal"],"steps":["Enquadramento","Documentação","Cartografia","Suficiência","Saída"],"questions":[["A potência de 3 MW, isoladamente, é suficiente para enquadrar o pedido em LAS?","nao"],["Um ponto isolado em KMZ delimita a ADA para a análise?","nao"],["Cabe diligência documental exigindo poligonais e arquivos geoespaciais completos?","sim"],["A ausência de poligonal impede a análise de APP e de supressão?","sim"],["O rito simplificado dispensa a verificação de suficiência documental?","nao"]],"outcome":"Não concluir a modalidade pela potência isolada: conferir também área de alagamento, IDA, supressão, sensibilidade e filtros territoriais. Independentemente do enquadramento, cabe diligência pelas poligonais completas da ADA, casa de força e reservatório antes do mérito."},
  {"id":"lp","track":"m05","label":"LP","type":"PCH","title":"Caso fictício de PCH em análise de viabilidade (LP)","facts":["Potência de 23,5 MW","Reservatório de 1,2 km²","EIA/RIMA apresentado","Alternativas locacionais avaliadas no estudo"],"evidence":["EIA e RIMA","Alternativas locacionais","Outorga preventiva / DRDH","Ata de audiência pública"],"steps":["Fase","Alternativas","Mérito","Participação","Ato"],"questions":[["A LP analisa localização e concepção, não a obra?","sim"],["A análise pode ignorar as alternativas locacionais do EIA?","nao"],["A audiência pública, quando exigível, integra a instrução da LP?","sim"],["A LP autoriza o início da instalação das estruturas?","nao"],["A conclusão pela viabilidade dispensa condicionantes para as fases seguintes?","nao"]],"outcome":"A LP decide viabilidade e concepção a partir do EIA e das alternativas; a instalação só vem com a LI. As condicionantes preparam a fase seguinte."},
  {"id":"li","track":"m05","label":"LI","type":"PCH","title":"LI com projeto executivo divergente da LP","facts":["Eixo da barragem deslocado cerca de 40 m","Cota do reservatório elevada em 1,5 m","ADA ampliada em relação à LP","Divergência não reavaliada pelo empreendedor"],"evidence":["Projeto executivo","Comparativo com a LP","Novo KMZ do arranjo","ART do projeto"],"steps":["Conformidade","Impacto novo","Reanálise","Registro","Saída"],"questions":[["A LI deve conferir se o projeto executivo corresponde ao concebido na LP?","sim"],["A ampliação da ADA e a nova cota são alterações relevantes?","sim"],["Alteração relevante do arranjo reabre análise proporcional?","sim"],["A divergência pode ser aceita sem registro por já existir a LP?","nao"],["A LI autoriza operar assim que a obra terminar?","nao"]],"outcome":"Reanálise proporcional da divergência antes de instalar: o que se instala tem de corresponder ao que se licenciou. Operar, só com a LO."},
  {"id":"lo","track":"m05","label":"LO","type":"PCH","title":"LO com as built e condicionantes de instalação","facts":["Obra concluída, com pequena divergência do as built em relação à LI","Duas condicionantes da LI sem comprovação anexada","Enchimento do reservatório ainda pendente de autorização","Programas ambientais em execução"],"evidence":["As built","Relatório de condicionantes da LI","Programas ambientais","Termo de enchimento"],"steps":["Correspondência","Condicionantes","Enchimento","Operação","Ato"],"questions":[["A LO verifica se o instalado corresponde ao licenciado (as built × LI)?","sim"],["Condicionante da LI sem comprovação pode ser dada por cumprida?","nao"],["O enchimento do reservatório depende de autorização específica?","sim"],["A LO pode ser emitida ignorando condicionantes pendentes da LI?","nao"],["A operação regular exige o cumprimento verificado das condicionantes?","sim"]],"outcome":"Exigir a comprovação das condicionantes da LI e a autorização de enchimento antes da LO. A operação regular pressupõe correspondência e cumprimento verificados."},
  {"id":"rlo","track":"m06","label":"RLO","type":"UHE","title":"Renovação de LO com fato novo e tempestividade a conferir","facts":["LO em vigor, operação há mais de 10 anos","O requerente informa protocolo 130 dias antes do vencimento; datas e regime aplicável ainda não foram conferidos","Criação de nova unidade de conservação no entorno","Automonitoramento em dia"],"evidence":["Licença vigente e comprovante de protocolo","Relatório de operação","Decreto da nova UC","Automonitoramento"],"steps":["Tempestividade","Fato novo","Reanálise","Condicionantes","Ato"],"questions":[["A informação de protocolo 130 dias antes, sem conferir datas e regime aplicável, basta para afirmar prorrogação da LO até a decisão?","nao"],["A criação de UC no entorno é fato novo a considerar na renovação?","sim"],["A renovação é ato automático quando o automonitoramento está em dia?","nao"],["Fato novo relevante pode gerar novas condicionantes na renovação?","sim"],["O status declarado pelo empreendedor equivale a status validado?","nao"]],"outcome":"Conferir a data do protocolo, o vencimento da licença e o regime aplicável antes de definir tempestividade e seus efeitos. Na análise da renovação, considerar a nova UC como fato novo e reavaliar condicionantes de modo proporcional. Nem o prazo informado nem o automonitoramento declarado autorizam conclusão automática."},
  {"id":"pacuera","track":"m09","label":"PACUERA","type":"UHE","title":"PACUERA de reservatório antigo com plano incompleto","facts":["Reservatório implantado nos anos 1990","Minuta de PACUERA sem zoneamento por UTHs","Sem registro de participação social","Usos já consolidados no entorno"],"evidence":["Minuta de PACUERA","Diagnóstico do entorno","Mapa de usos consolidados","Termo de Referência do PACUERA"],"steps":["Exigibilidade","Diagnóstico","Zoneamento","Participação","Implementação"],"questions":[["O PACUERA exige diagnóstico integrado do entorno do reservatório?","sim"],["O zoneamento pode ser aprovado sem as unidades territoriais (UTHs)?","nao"],["A participação social é etapa exigível do PACUERA?","sim"],["Usos consolidados dispensam o zoneamento e as regras de uso?","nao"],["A aprovação deve prever implementação, indicadores e revisão?","sim"]],"outcome":"Exigir diagnóstico, zoneamento por UTHs, participação social e plano de implementação e revisão. O PACUERA é gestão contínua do território, não um anexo formal."},
  {"id":"rlo-vencida","track":"m06","label":"Renovação de LO","type":"PCH","title":"PCH com tempestividade alegada e condicionantes sem evidência","facts":["12,8 MW em operação há 9 anos","A LO consta como vencida há 4 meses; o relatório afirma protocolo da renovação 130 dias antes, sem comprovação conferida","Relatório declara 100% das condicionantes cumpridas, sem anexos","Notificações anteriores no histórico"],"evidence":["Licença anterior e comprovante de protocolo","Relatório de cumprimento de condicionantes","Automonitoramento dos últimos 2 anos","Notificações anteriores"],"ausentes":["Anexos comprobatórios das condicionantes declaradas cumpridas","Comprovante conferido do protocolo da renovação"],"steps":["Tempestividade","Status","Evidência","Automonitoramento","Conclusão"],"questions":[["A afirmação de protocolo 130 dias antes, sem conferir a licença e o comprovante, basta para reconhecer a tempestividade e seus efeitos?","nao"],["Status declarado (100%) equivale a status validado?","nao"],["A análise deve exigir evidência por condicionante antes de concluir?","sim"],["Automonitoramento em dia supre a comprovação das demais condicionantes?","nao"],["Sem confirmar tempestividade, regime aplicável e eventuais impedimentos, é seguro concluir que a operação permanece regular?","nao"]],"outcome":"Não concluir prorrogação nem regularidade operacional apenas pelo prazo declarado. Conferir licença, protocolo, regime aplicável e eventuais impedimentos; depois avaliar cada condicionante com sua evidência e confrontar o resultado com o histórico de notificações."},
  {"id":"geo-insuficiente","track":"m10","label":"Cartografia","type":"PCH","title":"LP com KMZ apenas da barragem","facts":["Pedido de LP para PCH de 22 MW","KMZ apresenta só o ponto da barragem","Casa de força, adução e reservatório sem delimitação","TVR de 3,1 km descrita apenas em texto"],"evidence":["Memorial descritivo","KMZ com ponto único","Carta-imagem sem camadas vetoriais","Descrição do arranjo"],"steps":["Objeto","Cartografia","Interferências","Suficiência","Saída"],"questions":[["Um ponto isolado delimita suficientemente o empreendimento?","nao"],["A análise de APP, supressão e interferências depende das poligonais?","sim"],["A TVR descrita só em texto dispensa a poligonal do trecho?","nao"],["Cabe diligência documental exigindo os arquivos geoespaciais completos?","sim"],["Sem a base espacial, é possível concluir o mérito locacional?","nao"]],"outcome":"Diligência para as poligonais completas (barragem, adução, casa de força, reservatório e TVR) antes do mérito locacional."},
  {"id":"cp-antiga","track":"m03","label":"CP vencida","type":"CGH","title":"LP apoiada em Consulta Prévia vencida","facts":["CGH de 3,2 MW protocola LP citando CP favorável de 4 anos atrás","A manifestação de CP tem validade de 24 meses, não prorrogável","A norma de enquadramento mudou após a CP","Memorial atualizado apresentado"],"evidence":["Manifestação da CP antiga","Memorial atualizado","Matriz de enquadramento vigente","Histórico do processo"],"steps":["Validade da CP","Norma vigente","Enquadramento","Transição","Ato"],"questions":[["A CP vencida ainda vincula o enquadramento atual?","nao"],["O enquadramento deve ser refeito pela norma vigente na data do protocolo da LP?","sim"],["A mudança normativa após a CP deve ser registrada com data e justificativa?","sim"],["A CP antiga pode ser citada como contexto histórico do processo?","sim"],["A CP vencida pode ser usada como aprovação de viabilidade?","nao"]],"outcome":"A LP é analisada com enquadramento novo pela norma vigente; a CP vencida vale como histórico, não como direito. Registrar a transição normativa com datas e justificativa."}
];

// Os cenarios novos entram depois dos originais e cada um recebe a rubrica da
// fundamentacao (elementos esperados e texto modelo) definida em labCases.js.
export{GRUPOS_LAB};
export const scenarios = [...CENARIOS_BASE, ...NOVOS_CENARIOS].map(c => ({
  ...c,
  ...(RUBRICAS[c.id] || {}),
  ...(TAREFAS_LAB[c.id]
    ? { taskRevision: LAB_TASK_REVISION, ...TAREFAS_LAB[c.id] }
    : {}),
}));
